### ISSUE TITLE
Error "AutoIndexed was not yet loaded" when adding new item to list

### ISSUE THREAD

**Issue by iseliweb** [pnp/pnpcore#1027]
## Category

- [x] Bug

## Describe the bug

I'm trying to add a new item to a list but when adding the item, the error "Property AutoIndexed was not yet loaded" is thrown.

Thanks for the help.

## Steps to reproduce

IList list = await ctx.Web.Lists.GetByServerRelativeUrlAsync("AbsoluteListUrl"l, l => l.Fields);
Dictionary<string, object> item = new Dictionary<string, object>();
// Adding data ommitted
var addedItem = await list.Items.AddAsync(item);

## Expected behavior

List item being added without exception.

## Environment details (*development & target environment*)

- **SDK version**: PnP.Framework 1.11.0
- **OS**: Windows Server 2019 (1809)
- **SDK used in**: ASP.Net Web app
- **Framework**: .NET 6.0
- **Browser(s)**: Chrome v107
- **Tooling**: Visual Studio 2022

### Stack Trace

   at PnP.Core.Model.TransientObject.GetValue[T](String propertyName)
   at PnP.Core.Model.SharePoint.Field.get_AutoIndexed()
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.DictionaryDefaultConverter`3.OnWriteResume(Utf8JsonWriter writer, TDictionary value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryWrite(Utf8JsonWriter writer, TDictionary dictionary, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.ListOfTConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.DictionaryDefaultConverter`3.OnWriteResume(Utf8JsonWriter writer, TDictionary value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryWrite(Utf8JsonWriter writer, TDictionary dictionary, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize(Object value, Type inputType, JsonSerializerOptions options)
   at PnP.Core.Model.SharePoint.ListItem.<<-ctor>b__2_2>d.MoveNext()
   at PnP.Core.Model.BaseDataModel`1.<AddAsync>d__34.MoveNext()
   at PnP.Core.Model.SharePoint.ListItemCollection.<AddAsync>d__6.MoveNext()

**Comment by jansenbe** [comment]
@iseliweb : I've just ran some of the test cases that do list item adding and they work fine. I think you've an issue because you're not correctly defining the fields you're adding? Did you see https://pnp.github.io/pnpcore/using-the-sdk/listitems-intro.html#adding-list-items, especially the notes on using the `StaticName` and casing?

**Comment by iseliweb** [comment]
@jansenbe : Thanks for your Feedback. Yes I was aware of the StaticName behavior.

I've finally found the issue after debugging each field separately. The problem was an UrlFieldValue instance where the Url property was set to null. In my eyes this should not cause an exception like this. What do you think about that?

**Comment by jansenbe** [comment]
@iseliweb : I'll consider throwing an exception to handle this case, when using an URL field you either pass the URL value or set the field to "" to clean the current value. Closing this issue now.

**Comment by iseliweb** [comment]
Thanks
