### ISSUE TITLE
Error when creating context using M365 group GUID

### ISSUE THREAD

**Issue by JakeStanger** [pnp/pnpcore#1114]
## Category

- [x] Bug

## Describe the bug

When creating a context object, using an M365 group GUID, the library may throw an error:

```
[2023-02-24T17:07:31.303Z] System.Private.CoreLib: Exception while executing function: Orchestrator_ProvisionTeam. System.Net.Http: This instance has already started one or more requests. Properties can only be modified before sending the first request.
[2023-02-24T17:07:31.311Z] 026a09fdb3da48bc9927c47873ded560: Function 'Orchestrator_ProvisionTeam (Activity)' failed with an error. Reason: System.InvalidOperationException: This instance has already started one or more requests. Properties can only be modified before s
ending the first request.
[2023-02-24T17:07:31.313Z]    at System.Net.Http.HttpClient.CheckDisposedOrStarted()
[2023-02-24T17:07:31.314Z]    at System.Net.Http.HttpClient.set_BaseAddress(Uri value)
[2023-02-24T17:07:31.315Z]    at PnP.Core.Services.MicrosoftGraphClient.UpdateBaseAddress(String authority)
[2023-02-24T17:07:31.316Z]    at PnP.Core.Services.PnPContextFactory.InitializeContextAsync(PnPContext context, PnPContextOptions options)
[2023-02-24T17:07:31.318Z]    at PnP.Core.Services.PnPContextFactory.CreateAsync(Guid groupId, IAuthenticationProvider authenticationProvider, CancellationToken cancellationToken, PnPContextOptions options)
[2023-02-24T17:07:31.319Z]    at PnP.Core.Services.PnPContextFactory.CreateAsync(Guid groupId, IAuthenticationProvider authenticationProvider, PnPContextOptions options)
[2023-02-24T17:07:31.320Z]    at PnP.Core.Services.PnPContextFactory.CreateAsync(Guid groupId, PnPContextOptions options)
// snip
```

This appears to be because the library is incorrectly tracking whether the base address has been updated when creating a Graph client.

## Steps to reproduce

I am not sure if the bug is specific to this case, but here's how I encountered it:

1. Create a context factory object. In this case, as a builder service on startup and authenticated using a certificate.
1. Using the factory, get the admin context & create a new SharePoint team site.
1. Using the factory, get the admin context (again*) & create a team for the group associated with the site.
1. Using the factory, get the context for the team using its GUID.

*necessary, since the operations are split across multiple orchestrated 'activity' functions.

## Expected behavior

The context should be created succesfully, or return a meaningful error if provided bad input(s).

## Environment details (*development & target environment*)

- **SDK version**: 1.8.0
- **OS**: Windows 11
- **SDK used in**:  Azure Functions app (testing locally)
- **Framework**: .NET 6
- **Tooling**: Jetbrains Rider

**Comment by jansenbe** [comment]
@JakeStanger : when you create the site in step 2 you get back the `PnPContext` to operate on that site, at that point the site already has a Group connected to it (as that's a prereq for being able to add a Team). Why do you want to load all again using the group id?

**Comment by JakeStanger** [comment]
This is because steps 2-4 are all separate Azure Functions, triggered by an orchestrator. The orchestrator can provide the factory since it's automagically injected, but functions can only take/return serializable data as arguments and (I think at least) there is no guarantee field values on the class level will persist if set by functions for similar reasons.

In short, the context is disposed of at the end of each function, so a new context is required at the start of each.

**Comment by jansenbe** [comment]
@JakeStanger : so the failure comes from https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/Services/Core/PnPContextFactory.cs#L467 and https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/Services/Core/Http/MicrosoftGraphClient.cs#L67-L74. How are you added the `IPnPContextFactory` to the dependency container in your function? Also, are you working with different graph backends from the same function?

note: I've just pushed a small update that only updates the base address when there's a true change, this might help already. This update will be part of the next nightly release (version 1.8.114 or higher)

![image](https://user-images.githubusercontent.com/7451219/221514286-f44217de-e440-4055-b652-0b5d30866cdf.png)

**Comment by jansenbe** [comment]
@JakeStanger : did things improve with the extra check in the code?

**Comment by JakeStanger** [comment]
Hey, sorry got distracted by other bits & only just tested this - it looks to have worked :)
