### ISSUE TITLE
Getting a ClientSidePage gives "The JSON value could not be converted to System.Int32"

### ISSUE THREAD

**Issue by PedroMordeP** [pnp/pnpcore#1180]
- [x] Bug

I'm using PnP.Framework 1.11.0 and when I'm provisioning a template and when is getting a page, pre-created by the framework, I'm getting the following error "The JSON value could not be converted to System.Int32. Path: $.position.sectionIndex | LineNumber: 0 | BytePositionInLine: 107."

This is happens on _return (await pnpContext.Web.GetPagesAsync(pageName).ConfigureAwait(false)).FirstOrDefault();_

I'm trying to debug to try to understand why this is happing on this specific Education Tenant. Any ideas what could be the cause for giving this error when getting a pre-crated page.

```
[2023-05-16T15:03:32.857Z] The JSON value could not be converted to System.Int32. Path: $.position.sectionIndex | LineNumber: 0 | BytePositionInLine: 107. | Reason: (JsonException) The JSON value could not be converted to System.Int32. Path: $.position.sectionIndex | LineNumber: 0 | BytePositionInLine: 107. | InnerException: System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
[2023-05-16T15:03:32.861Z]    at System.Text.Json.Utf8JsonReader.GetInt32()
[2023-05-16T15:03:32.862Z]    at System.Text.Json.Serialization.Converters.JsonConverterInt32.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
[2023-05-16T15:03:32.863Z]    at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
[2023-05-16T15:03:32.864Z]    at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
[2023-05-16T15:03:32.866Z]    at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
[2023-05-16T15:03:32.867Z]
[2023-05-16T15:03:32.868Z] --- StackTrace:    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, Utf8JsonReader& reader, Exception ex)
[2023-05-16T15:03:32.869Z]    at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
[2023-05-16T15:03:32.870Z]    at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
[2023-05-16T15:03:32.871Z]    at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
[2023-05-16T15:03:32.872Z]    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
[2023-05-16T15:03:32.873Z]    at PnP.Core.Model.SharePoint.CanvasControl.GetType(String controlDataJson)
[2023-05-16T15:03:32.874Z]    at PnP.Core.Model.SharePoint.Page.LoadFromHtml(String html, String pageHeaderHtml)
[2023-05-16T15:03:32.886Z]    at PnP.Core.Model.SharePoint.Page.LoadPageAsync(IList pagesLibrary, IListItem item)
[2023-05-16T15:03:32.887Z]    at PnP.Core.Model.SharePoint.Page.LoadPagesAsync(PnPContext context, String pageName)
[2023-05-16T15:03:32.889Z]    at PnP.Core.Model.SharePoint.Web.GetPagesAsync(String pageName)
[2023-05-16T15:03:32.893Z]    at Microsoft.SharePoint.Client.PageExtensions.LoadClientSidePageAsync(Web web, String pageName) in C:\B\Repos\BindTuning.PnP.Framework\src\lib\PnP.Framework\Extensions\PageExtensions.cs:line 878
[2023-05-16T15:03:32.903Z]    at Microsoft.SharePoint.Client.PageExtensions.LoadClientSidePage(Web web, String pageName) in C:\B\Repos\BindTuning.PnP.Framework\src\lib\PnP.Framework\Extensions\PageExtensions.cs:line 890
[2023-05-16T15:03:32.907Z]    at PnP.Framework.Provisioning.ObjectHandlers.ObjectClientSidePages.CreatePage(Web web, ProvisioningTemplate template, TokenParser parser, PnPMonitoredScope scope, BaseClientSidePage clientSidePage, String pagesLibrary, List pagesLibraryList, Int32& currentPageIndex, List`1 preCreatedPages) in C:\B\Repos\BindTuning.PnP.Framework\src\lib\PnP.Framework\Provisioning\ObjectHandlers\ObjectClientSidePages.cs:line 353
[2023-05-16T15:03:32.915Z]    at PnP.Framework.Provisioning.ObjectHandlers.ObjectClientSidePages.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation) in C:\B\Repos\BindTuning.PnP.Framework\src\lib\PnP.Framework\Provisioning\ObjectHandlers\ObjectClientSidePages.cs:line 162
[2023-05-16T15:03:32.918Z]    at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser) in C:\B\Repos\BindTuning.PnP.Framework\src\lib\PnP.Framework\Provisioning\ObjectHandlers\SiteToTemplateConversion.cs:line 455
[2023-05-16T15:03:32.919Z]    at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation) in C:\B\Repos\BindTuning.PnP.Framework\src\lib\PnP.Framework\Extensions\WebExtensions.cs:line 1182
```

**Comment by carlosmiguelsns** [comment]
@PedroMordeP if you update the PnP.Core nuget to the latest version 1.9, it should fix the issue! 

`  <PackageReference Include="PnP.Core" Version="1.9.0" Condition="'$(PnPCoreSdkPath)' == ''" />`

**Comment by PedroMordeP** [comment]
Updated to 1.9 and is working. 🤦
