### ISSUE TITLE
The target view cannot be configured as a mobile view.

### ISSUE THREAD

**Issue by PedroMordeP** [pnp/pnpcore#1195]
## Category

- [x] Bug

When deploying a template with a view with parameters **MobileView="TRUE"**  and **Type="GRID"** gives a ServerException.

If the MobileView is changed to "False" or the Type to "HTML" it **works**. Like
- **MobileView="FALSE"**  and **Type="GRID"**
- **MobileView="TRUE"**  and **Type="HTML"**
- 
Is there any reason why this is not accepted?

Example
            `<View Name="{DAB0E315-6F4A-412C-9287-285F67B3B482}" MobileView="TRUE" Type="GRID" DisplayName="All Items" Url="{site}/Lists/Event Itinerary/All Items.aspx" Level="1" ContentTypeID="0x">`

Is there any reason why this is not accepted?

Error

```
(ServerException) The target view cannot be configured as a mobile view.

 --- Server Error Details:
 - ServerErrorCode: -2146232832
 - ServerErrorTraceCorrelationId: 4d94b8a0-908a-6000-a328-75f154a12cc7
 - ServerErrorTypeName: Microsoft.SharePoint.SPException
 - Source: Microsoft.SharePoint.Client.Runtime

 --- StackTrace:    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
    at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
    at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
    at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
    at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
    at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
    at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
    at PnP.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateView(Web web, View view, ViewCollection existingViews, List createdList, PnPMonitoredScope monitoredScope, TokenParser parser, Int32 currentViewIndex, Int32 total)
    at PnP.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProcessViews(Web web, TokenParser parser, PnPMonitoredScope scope, ListInfo listInfo)
    at PnP.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
    at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo, Boolean calledFromHierarchy, TokenParser tokenParser)
```

**Comment by jansenbe** [comment]
@PedroMordeP : this seems to be an issue coming via PnP Framework (as I see the provisioning engine code paths). This feels like a SharePoint issue and not an issue in the SDK's
