### ISSUE TITLE
File Not Found when Adding to Folder

### ISSUE THREAD

**Issue by stumpykilo** [pnp/pnpcore#1199]
## Category

- [x] Bug

## Describe the bug

When adding a file (as a `MemoryStream`) to a folder a `HttpResponseCode: 404` is thrown. I have verified the `GetFolderByServerRelativeUrlAsync` and the `MemoryStream` are working correctly.

## Steps to reproduce

```
            var memoryStream = new MemoryStream();
            var downloadResponse = await blobClient.DownloadToAsync(memoryStream);
            memoryStream.Position = 0;
            var fileSize = memoryStream.Length;
            
            _logger.LogInformation($"{model.Filename} fetched from Blob Storage and is {fileSize} Bytes in size");

            string folderUrl = $"{context.Uri.PathAndQuery}/{model.ProjectName}/Shared Documents";
            IFolder folder = await context.Web.GetFolderByServerRelativeUrlAsync(folderUrl);
            IFile newFile = await folder.Files.AddAsync(model.Filename, memoryStream, true);

            _logger.LogInformation($"{model.Filename} uploaded to Sharepoint");
```

## Expected behavior

I expect that `newFile` should be populated after the file is uploaded to the Sharepoint folder.

## Environment details (*development & target environment*)

- **SDK version**: v.1.9.0
- **OS**: Windows 11
- **SDK used in**: v4 isolated-process Azure Function
- **Framework**: .NET 6
- **Browser(s)**: Chrome v114.0.5735.110
- **Tooling**: VS Code v1.78.2

### Additional context

Here is console output
```
[2023-06-08T15:37:53.287Z] Test3.txt fetched from Blob Storage and is 35 Bytes in size
[2023-06-08T15:37:53.292Z] Retrieved access token for resource UsernamePasswordAuthenticationProvider with scopes 'https://contoso.sharepoint.com/sites/contoso_pwa' from , https://contoso.sharepoint.com/.default
[2023-06-08T15:37:53.293Z] Start processing HTTP request GET https://contoso.sharepoint.com/sites/contoso_pwa/_api/Web/getFolderByServerRelativePath(decodedUrl='%2Fsites%2Fcontoso_pwa%2FMycontosoPlatform_Dev%2FShared Documents')
[2023-06-08T15:37:53.293Z] Sending HTTP request GET https://contoso.sharepoint.com/sites/contoso_pwa/_api/Web/getFolderByServerRelativePath(decodedUrl='%2Fsites%2Fcontoso_pwa%2FMycontosoPlatform_Dev%2FShared Documents')
[2023-06-08T15:37:53.388Z] Received HTTP response headers after 93.8209ms - 200
[2023-06-08T15:37:53.389Z] End processing HTTP request after 95.5917ms - 200
[2023-06-08T15:37:53.394Z] Retrieved access token for resource UsernamePasswordAuthenticationProvider with scopes 'https://contoso.sharepoint.com/sites/contoso_pwa' from , https://contoso.sharepoint.com/.default
[2023-06-08T15:37:53.394Z] Start processing HTTP request POST https://contoso.sharepoint.com/sites/contoso_pwa/_api/web/getFolderById('a9116c82-00e5-4d05-a33e-7f5d521801ef')/files/addusingpath(decodedUrl='Test3.txt',overwrite=true)
[2023-06-08T15:37:53.395Z] Sending HTTP request POST https://contoso.sharepoint.com/sites/contoso_pwa/_api/web/getFolderById('a9116c82-00e5-4d05-a33e-7f5d521801ef')/files/addusingpath(decodedUrl='Test3.txt',overwrite=true)
[2023-06-08T15:37:53.496Z] Received HTTP response headers after 99.9592ms - 404
[2023-06-08T15:37:53.497Z] End processing HTTP request after 101.1215ms - 404
[2023-06-08T15:38:08.363Z] Executed 'Functions.UploadBlobEventHubTrigger' (Failed, Id=df1e4c76-e4e0-44c8-931f-a7823b78f367, Duration=30026ms)
[2023-06-08T15:38:08.365Z] System.Private.CoreLib: Exception while executing function: Functions.UploadBlobEventHubTrigger. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (SharePoint Rest service exception)
[2023-06-08T15:38:08.366Z]  ---> HttpResponseCode: 404
[2023-06-08T15:38:08.367Z] Code: System.IO.FileNotFoundException
[2023-06-08T15:38:08.367Z] Message: File Not Found.
[2023-06-08T15:38:08.368Z] ClientRequestId: 51ddbaa0-d020-3000-af22-7f7666f6baab
[2023-06-08T15:38:08.369Z] SPClientServiceRequestDuration: 17
[2023-06-08T15:38:08.370Z] X-SharePointHealthScore: 2
[2023-06-08T15:38:08.371Z] X-SP-SERVERSTATE: ReadOnly=0
[2023-06-08T15:38:08.373Z]
[2023-06-08T15:38:08.373Z] PnP.Core.SharePointRestServiceException: SharePoint Rest service exception
[2023-06-08T15:38:08.374Z]    at PnP.Core.Services.BatchClient.ExecuteSharePointRestInteractiveAsync(Batch batch)
[2023-06-08T15:38:08.375Z]    at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
[2023-06-08T15:38:08.378Z]    at PnP.Core.Model.BaseDataModel`1.RequestAsync(ApiCall apiCall, HttpMethod method, String operationName)  
[2023-06-08T15:38:08.379Z]    at PnP.Core.Model.SharePoint.FileCollection.FileUpload(File newFile, Stream content, Boolean overwrite)   
[2023-06-08T15:38:08.379Z]    at PnP.Core.Model.SharePoint.FileCollection.AddAsync(String name, Stream content, Boolean overwrite)      
[2023-06-08T15:38:08.381Z]    at contosoPlatform.EventHub.Functions.Blobs.UploadBlobEventHubTrigger.Run(String[] input) in C:\src\contosoExperienceAPIServices\contosoPlatform.EventHub\Functions\Blobs\UploadBlobEventHubTrigger.cs:line 130
[2023-06-08T15:38:08.382Z]    --- End of inner exception stack trace ---
[2023-06-08T15:38:08.383Z]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2023-06-08T15:38:08.384Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2023-06-08T15:38:08.385Z]    at System.Threading.Tasks.Task`1.get_Result()
[2023-06-08T15:38:08.386Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2023-06-08T15:38:08.387Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2023-06-08T15:38:08.389Z]    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
[2023-06-08T15:38:08.390Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-06-08T15:38:08.391Z] --- End of stack trace from previous location ---
[2023-06-08T15:38:08.391Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)     
[2023-06-08T15:38:08.392Z] --- End of stack trace from previous location ---
[2023-06-08T15:38:08.393Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2023-06-08T15:38:08.395Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-06-08T15:38:08.396Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider, IInputConversionFeatureProvider functionInputConversionFeatureProvider) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 199
Stack:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2023-06-08T15:38:08.397Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2023-06-08T15:38:08.398Z]    at System.Threading.Tasks.Task`1.get_Result()
[2023-06-08T15:38:08.399Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2023-06-08T15:38:08.400Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2023-06-08T15:38:08.401Z]    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
[2023-06-08T15:38:08.402Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-06-08T15:38:08.403Z] --- End of stack trace from previous location ---
[2023-06-08T15:38:08.404Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)     
[2023-06-08T15:38:08.405Z] --- End of stack trace from previous location ---
[2023-06-08T15:38:08.405Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 44
[2023-06-08T15:38:08.406Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-06-08T15:38:08.407Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider, IInputConversionFeatureProvider functionInputConversionFeatureProvider) in D:\a\_work\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 199.
```

**Comment by stumpykilo** [comment]
Yes, I'm running this function locally. I have not used Fiddler in a while, is there a trick to allow sharepoint calls to be tracked? I see my calls going out to Azure over HTTPS just find but none for sharepoint.

**Comment by stumpykilo** [comment]
@jansenbe  does this line `Start processing HTTP request POST https://contoso.sharepoint.com/sites/contoso_pwa/_api/web/getFolderById('a9116c82-00e5-4d05-a33e-7f5d521801ef')/files/addusingpath(decodedUrl='Test3.txt',overwrite=true)` look right? If you notice the location of the folder I have retrieved `Sending HTTP request GET https://contoso.sharepoint.com/sites/contoso_pwa/_api/Web/getFolderByServerRelativePath(decodedUrl='%2Fsites%2Fcontoso_pwa%2FMycontosoPlatform_Dev%2FShared Documents')` it lives on a "subsite" of the `contoso_pwa` site.

**Comment by stumpykilo** [comment]
@jansenbe  I changed my line 
`IFile newFile = await folder.Files.AddAsync(model.Filename, memoryStream, true);` 
to 
`IFile newFile = await folder.Files.AddAsync($"Shared Documents/{model.Filename}", memoryStream, true);` 
and it succesfully uploaded but to the `contoso_pwa` "Shared Documents" instead of the "MycontosoPlatform_Dev/Shared Documents". Any ideas?

**Comment by jansenbe** [comment]
A PnPContext is scoped to a (sub) site, you need to clone your context for the subsite url. Alternatively you can just create a new context from scratch

**Comment by stumpykilo** [comment]
Ah, I see. Can you point me to documentation on how to create contexts properly? We will need that ability because our (sub) sites are created dynamically.

**Comment by jansenbe** [comment]
@stumpykilo : Sure, see https://pnp.github.io/pnpcore/using-the-sdk/basics-context.html#cloning-a-pnpcontext-for-a-new-web

**Comment by jansenbe** [comment]
@stumpykilo : yes, the first variable is just the filename. So like this:

```csharp
await folder.Files.AddAsync("testchunked_added.docx", new MemoryStream(System.IO.File.ReadAllBytes($".{Path.DirectorySeparatorChar}TestAssets{Path.DirectorySeparatorChar}testchunked.docx")), true);
```

**Comment by jansenbe** [comment]
@stumpykilo : let me know when you're unblocked so that the issue can be closed

**Comment by stumpykilo** [comment]
I will check tomorrow

**Comment by stumpykilo** [comment]
@jansenbe all good, thank you! Closing now.
