### ISSUE TITLE
Updating propertybag values doesn't work

### ISSUE THREAD

**Issue by danielpastoor** [pnp/pnpcore#1249]
## Category

- [x] Bug

## Describe the bug

When I try to add a property then it returns a CSOM error:

```
HttpResponseCode: 200
Message: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
ClientRequestId: aa0dcfa0-50e5-7000-114d-4ff47281be1e
ErrorTypeName: "System.UnauthorizedAccessException"

PnP.Core.CsomServiceException: CSOM service exception
   at PnP.Core.Services.BatchClient.ProcessCsomBatchResponse(CsomBatch csomBatch, String batchResponse, HttpStatusCode statusCode)
   at PnP.Core.Services.BatchClient.ExecuteCsomBatchAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Model.BaseDataModel`1.RequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
   at PnP.Core.Model.BaseDataModel`1.RawRequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
   at PnP.Core.Model.SharePoint.PropertyValues.UpdateAsync()
```

## Steps to reproduce

```
var web = await context.Web.GetAsync(x => x.AllProperties);
web.AllProperties["test"] = "test";
await web.AllProperties.UpdateAsync();
```

## Expected behavior

That it updates

## Environment details (*development & target environment*)

development

**Comment by danielpastoor** [comment]
Found the issue. Is is required to set noScriptSite to false
