### ISSUE TITLE
Error executing Get-PnPAzureACSPrincipal when including -IncludeSubsites switch

### ISSUE THREAD

**Issue by joerodgers** [pnp/pnpcore#1267]
## Category

- [x] Bug

## Describe the bug

Execution of ```Get-PnPAzureACSPrincipal -Scope All -IncludeSubsites -ErrorAction Stop ``` throws error:

```Get-PnPAzureACSPrincipal: Value cannot be null. (Parameter 'source')```

### Additional context

```
PS C:\Users\xxx> Get-PnPAzureACSPrincipal -Scope All -IncludeSubsites -ErrorAction Stop
Get-PnPAzureACSPrincipal: Value cannot be null. (Parameter 'source')

PS C:\Users\xxx> $error[0] | FL * -Force

ErrorRecord                 : Value cannot be null. (Parameter 'source')
WasThrownFromThrowStatement : False
TargetSite                  : System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] Invoke(System.Collections.IEnumerable)
Message                     : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Value cannot be null. (Parameter 'source')
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              :
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087
StackTrace                  :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown, ExecutionOptions options)


PS C:\Users\xxxx> $error[1] | FL * -Force

PSMessageDetails      :
Exception             : System.ArgumentNullException: Value cannot be null. (Parameter 'source')
                           at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
                           at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
                           at PnP.Core.Admin.Model.SharePoint.LegacyPrincipalManagement.<>c.<GetACSPrincipalsAsync>b__4_1(LegacyPrincipal p)
                           at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
                           at PnP.Core.Admin.Model.SharePoint.LegacyPrincipalManagement.GetACSPrincipalsAsync(PnPContext context, List`1 legacyServicePrincipals, Boolean includeSubsites, Boolean tenantOnly, VanityUrlOptions
                        vanityUrlOptions)
                           at PnP.Core.Admin.Model.SharePoint.SiteCollectionManager.GetTenantAndSiteCollectionACSPrincipalsAsync(List`1 legacyServicePrincipals, Boolean includeSubsites, VanityUrlOptions vanityUrlOptions)
                           at PnP.Core.Admin.Model.SharePoint.SiteCollectionManager.GetTenantAndSiteCollectionACSPrincipals(List`1 legacyServicePrincipals, Boolean includeSubsites, VanityUrlOptions vanityUrlOptions)
                           at PnP.PowerShell.Commands.Apps.GetAzureACSPrincipal.ExecuteCmdlet() in c:\build\src\Commands\Apps\GetAzureACSPrincipal.cs:line 53
                           at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord() in c:\build\src\Commands\Base\PnPConnectedCmdlet.cs:line 53
TargetObject          :
CategoryInfo          : WriteError: (:) [Get-PnPAzureACSPrincipal], ArgumentNullException
FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Apps.GetAzureACSPrincipal
ErrorDetails          : Value cannot be null. (Parameter 'source')
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

PS C:\Users\xxx> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.13
PSEdition                      Core
GitCommitId                    7.2.13
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\xxx> get-module pnp.powershell | FL Name, Version

Name    : pnp.powershell
Version : 2.2.0
```

**Comment by jansenbe** [comment]
@joerodgers : I'm currently integrating these APIs (Azure ACS + SharePoint AddIn detection) into the Microsoft 365 Assessment tool and found some other issues as well. Will push an update later next week with improvements. Thanks for raising this!

**Comment by jansenbe** [comment]
@joerodgers : do you still see this issue with the recent PnP PS builds?

**Comment by jansenbe** [comment]
Closing for now @joerodgers , if it still goes wrong it's most likely an issue in PnP PS
