### ISSUE TITLE
The query string "DecodedUrl" is missing or invalid.

### ISSUE THREAD

**Issue by danielpastoor** [pnp/pnpcore#1297]
## Category

- [x] Bug

## Describe the bug

When I try to save a SharePoint page then I get this error:

HttpResponseCode: 400
Code: Microsoft.SharePoint.Client.InvalidClientQueryException
Message: The query string "DecodedUrl" is missing or invalid.
ClientRequestId: 70ace4a0-d08e-7000-6b3c-3d6a10f93118
SPClientServiceRequestDuration: 13
X-SharePointHealthScore: 0
X-SP-SERVERSTATE: ReadOnly=0

PnP.Core.SharePointRestServiceException: SharePoint Rest service exception
   at PnP.Core.Services.BatchClient.ExecuteSharePointRestInteractiveAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteSharePointRestBatchAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Model.BaseDataModel`1.BaseRetrieveAsync(ApiCall apiOverride, Func`2 fromJsonCasting, Action`1 postMappingJson, Expression`1[] expressions)
   at PnP.Core.Model.SharePoint.Web.GetFileByServerRelativeUrlAsync(String serverRelativeUrl, Expression`1[] expressions)
   at PnP.Core.Model.SharePoint.Web.GetFileByServerRelativeUrlOrDefaultAsync(String serverRelativeUrl, Expression`1[] expressions)

## Steps to reproduce

Save a page. 

## Expected behavior

No Error

## Environment details (*development & target environment*)

- **OS**: 7MacOS 14
- **SDK used in**: Console App 
- **Framework**: .NET Core 7 ]
- **Nuget version: 1.10.103-nightly

### Additional context

I do think it is related to #1290

**Comment by jansenbe** [comment]
@danielpastoor : this indeed is a regression from the recent change. Working on it...

**Comment by jansenbe** [comment]
@danielpastoor : can you try tomorrow with the next nightly and see if the issue is resolved for you?

**Comment by danielpastoor** [comment]
Yes I will try it thank you

**Comment by danielpastoor** [comment]
I have tested the fix and it does work now. Thank you
