### ISSUE TITLE
Unable to update ListItem with DateTime property

### ISSUE THREAD

**Issue by kavrat** [pnp/pnpcore#1488]
## Category

- [x] Bug

## Describe the bug

 I'm trying to update a listitem with the DateTime property with a new value in UTC format, but I got an error:
>Exception: System.ArgumentException: Unknown timezone mapping
[2024-06-20T15:19:08.619Z]    at PnP.Core.Model.SharePoint.TimeZone.GetTimeZoneInfoFromSharePoint(Int32 timeZoneId)
[2024-06-20T15:19:08.619Z]    at PnP.Core.Model.SharePoint.TimeZone.UtcDelta(DateTime dateTime)
[2024-06-20T15:19:08.620Z]    at PnP.Core.Model.SharePoint.TimeZone.UtcToLocalTime(DateTime dateTime)
[2024-06-20T15:19:08.621Z]    at PnP.Core.Model.SharePoint.ListItem.DateTimeToSharePointWebDateTimeString(PnPContext context, DateTime input)
[2024-06-20T15:19:08.622Z]    at PnP.Core.Model.SharePoint.ListItem.BuildValidateUpdateItemPayload(PnPContext context, KeyValuePair`2 changedProp, Object field)
[2024-06-20T15:19:08.622Z]    at CallSite.Target(Closure, CallSite, ListItem, PnPContext, KeyValuePair`2, Object)
[2024-06-20T15:19:08.623Z]    at PnP.Core.Model.SharePoint.ListItem.BuildUpdateApiCallAsync(PnPContext context)
[2024-06-20T15:19:08.624Z]    at PnP.Core.Model.SharePoint.ListItem.BaseUpdate(Func`2 fromJsonCasting, Action`1 postMappingJson)
[2024-06-20T15:19:08.625Z]    at PnP.Core.Model.BaseDataModel`1.UpdateAsync()

TimeZone of SharePoint site - (UTC-12:00 International Date Line West)
Locale - German

## Expected behavior

ListItem should be updated as expected

## Environment details (*development & target environment*)

- **SDK version**: 1.12
- **OS**: Windows 11
- **SDK used in**: Azure Functions
- **Framework**: .NET 8.0
- **Tooling**:Rider IDE

**Comment by jansenbe** [comment]
@kavrat : I've tried to reproduce this but am failing to do so. Can you show the code you use to update the ListItem? Do you seen the same issue on with other timezones/languages as well?

**Comment by kavrat** [comment]
@jansenbe 
This is a working variant. 
`input.Timestamp` is DateTime type. Without `.ToString("u")` it doesn't work.
```

                    List<IListItem> filteredFormRules = formRules
                        .Where(li =>
                            li.Values[BuiltIn.SharePoint.FormPrefix].ToString() ==
                            input.FormPrefix)
                            .ToList();

                    foreach (IListItem formRule in filteredFormRules)
                    {
                        formRule.Values[BuiltIn.SharePoint..ExecutionResults] =
                            JsonSerializer.Serialize(executionResults, new JsonSerializerOptions { WriteIndented = true });
                        formRule.Values[BuiltIn.SharePoint.FormLastRun] = input.Timestamp.ToString("u");

                        await formRule.UpdateAsync();
                    }

 ```
