### ISSUE TITLE
AvailablePageComponents - A concurrent update was performed on this collection and corrupted its state

### ISSUE THREAD

**Issue by DeloitteKedmiDor** [pnp/pnpcore#1490]
## Category

- [x] Bug

## Describe the bug

Using PnP.Core.Model.SharePoint.Page.AvailablePageComponents method it thrown an exception:
**Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct**. StackTrace:    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
[06/25/2024 05:02:55 > 975e68: INFO]          at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
[06/25/2024 05:02:55 > 975e68: INFO]          at PnP.Core.Model.BaseDataModel`1.RequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
[06/25/2024 05:02:55 > 975e68: INFO]          at PnP.Core.Model.BaseDataModel`1.RawRequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
[06/25/2024 05:02:55 > 975e68: INFO]          at PnP.Core.Model.SharePoint.Page.AvailablePageComponentsAsync(String name)
[06/25/2024 05:02:55 > 975e68: INFO]          at PnP.Core.Model.SharePoint.Page.AvailablePageComponents(String name)

## Steps to reproduce

![image](https://github.com/pnp/pnpcore/assets/152775965/90cbcbe1-7a46-4078-9743-8aac09149567)

## Expected behavior

return list of available page components

## Environment details (*development & target environment*)

- **OS**: [ Windows 10 ]
- **SDK used in**: [ Console App ]
- **Framework**: [ .NET Core v8 ]

**Comment by jansenbe** [comment]
Hey @DeloitteKedmiDor : I'm not able to reproduce this. Does this still reproduce for you?

![image](https://github.com/user-attachments/assets/b150fe93-9122-40fc-8e7d-323267107131)

**Comment by jansenbe** [comment]
Closing per no response, please re-open if still needed @DeloitteKedmiDor
