### ISSUE TITLE
LoadListDataAsStreamAsync: System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'String'.

### ISSUE THREAD

**Issue by 2Who** [pnp/pnpcore#1588]
## Category

- [x] Bug

## Describe the bug
We have a SharePoint Online document library and for some documents the function "LoadListDataAsStream" runs into an error.
The problem seems to be related to the the metadata fields of the documents.
Unlike issue #1365 we don't use any image field data or location field data.

We call the function like this: 
```
List.LoadListDataAsStream(new RenderListDataOptions()
{
    ViewXml = ViewXml,
    RenderOptions = RenderListDataOptionsFlags.ListData
});
```
The ViewXML looks like this: 
```
<View>
	<Query>
		<Where>
			<In>
				<FieldRef Name='ID'/>
				<Values>
					<Value Type='Number'>40</Value>
				</Values>
			</In>
		</Where>
	</Query>
</View>
```

The error message is System.InvalidOperationException: 

> 'The requested operation requires an element of type 'Object', but the target element has type 'String'.'

And the stacktrace of the error is:

>    at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
>    at System.Text.Json.JsonElement.EnumerateObject()
>    at PnP.Core.Model.SharePoint.ListDataAsStreamHandler.TransformRowData(JsonElement row, IFieldCollection fields, Dictionary`2 fieldLookupCache)
>    at PnP.Core.Model.SharePoint.ListDataAsStreamHandler.<Deserialize>d__1.MoveNext()
>    at PnP.Core.Model.SharePoint.List.<LoadListDataAsStreamAsync>d__198.MoveNext()
>    at PnP.Core.Model.SharePoint.List.LoadListDataAsStream(RenderListDataOptions renderOptions)

## Steps to reproduce

Since the error is specific to documents within our company and without knowing what the underlying problem is, I can't provide steps to reproduce.

## Expected behavior

Loading the list items without an error.

## Environment details (*development & target environment*)

- **SDK version**: [1.14.0]
- **OS**: [Windows 10]
- **SDK used in**: [Console App]
- **Framework**: [.NET 8.0 ]
- **Tooling**: [Visual Studio 2022]
- **SharePoint environment**: [SharePoint Online]

### Additional context
We are migrating documents from SharePoint 2019 to SharePoint Online.

**Comment by jansenbe** [comment]
@2Who : do you have an option to capture a Fiddler trace when reproducing, that will show the payload we get back from SharePoint. The code that processes the metadata payload seems to be failing, without understanding those details it will be really hard to repro/fix.

**Comment by jansenbe** [comment]
@2Who : closing per no feedback, please re-open or create a new issue with more details in case you still have this issue

**Comment by vladimirwerskov** [comment]
I have recently received the same error on a custom list which contained a User field (Responsible). Some of the documents contained an invalid field and this caused the issue.
The SharePoint was not able to display the user and displayed just an empty string. The lookup id contained a number which was not in the SiteUsers.

If I have called LoadListDataAsStream on this list, the above exception was thrown.
I have debugged the code and in ListDataAsStreamHandler::TransformRowData the following variables were set for the Responsible field:

+		field	TypeAsString = "User"	PnP.Core.Model.SharePoint.IField {PnP.Core.Model.SharePoint.Field}
+		property	""Responsible": [""]"	System.Text.Json.JsonProperty

As an experiment I have checked for empty string and it stopped throwing the exception:

                                if (streamPropertyElement.ValueKind == JsonValueKind.String && string.IsNullOrEmpty(streamPropertyElement.GetString()))
                                {
                                }
                                else
                                {
                                    foreach (var streamPropertyElementValue in streamPropertyElement.EnumerateObject())
                                    {
                                        listDataAsStreamPropertyValue.Properties.Add(streamPropertyElementValue.Name, GetJsonPropertyValueAsString(streamPropertyElementValue.Value));
                                    }

                                    streamProperty.Values.Add(listDataAsStreamPropertyValue);
                                }
