### ISSUE TITLE
SharePoint Rest service exception produced when trying to connect to SharePoint site using a different case (lower versus upper) in the URL.

### ISSUE THREAD

**Issue by jscarano** [pnp/pnpcore#226]
## Category

- [x] Bug

## Describe the bug

If I have a site in SharePoint online that has capital letters in the URL

```
    https://mytenant.sharepoint.com/sites/TEST-MixedCase
```

And I try to use a different case (say lower case) 
```
    https://mytenant.sharepoint.com/sites/test-mixedcase
```

The code throws an exception (SharePoint Rest service exception)

```
   at PnP.Core.Services.BatchClient.ProcessSharePointRestBatchResponseContent(Batch batch, String batchResponse)
   at PnP.Core.Services.BatchClient.<ProcessSharePointRestBatchResponse>d__48.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Services.BatchClient.<ExecuteSharePointRestBatchAsync>d__46.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Services.BatchClient.<ExecuteBatch>d__37.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Services.PnPContext.<ExecuteAsync>d__86.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.QueryModel.DataModelQueryService`1.<ExecuteQueryAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.QueryModel.BaseQueryProvider.<CastTask>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.QueryModel.BaseDataModelExtensions.<BaseLinqGetAsync>d__11`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Model.SharePoint.ListCollection.<GetByTitleAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Demo.AzureFunction.GetSiteDocuments.<Run>d__2.MoveNext() in C:\Projects\Demo.AzureFunction\GetSiteDocuments.cs:line 36
```

## Steps to reproduce

1. Create a site in SharePoint online named "TEST-MixedCase". Note the URL should be "/sites/TEST-MixedCase"
2. Use the following code to create a context and the try to get list details.

```C#
    Uri siteUrl = new Uri("https://mytenant.sharepoint.com/sites/test-mixedcase");
    using (var pnpContext = await pnpContextFactory.CreateAsync(siteUrl))
    {
        try
        {
            IList sharedDocuments = await pnpContext.Web.Lists.GetByTitleAsync("Documents", l => l.RootFolder);

        }
        catch (Exception ex)
        {
            return new BadRequestObjectResult(new { message = ex.Message });
        }

    }
```

## Expected behavior

The case of a URL should not matter when connecting to a SharePoint site. 

## Environment details (*development & target environment*)

- **SDK version**: 0.3.34-preview3
- **OS**: Windows 10
- **SDK used in**: Azure Function v3
- **Framework**:  .NET Core v3.1
- **Browser(s)**: N/A]
- **Tooling**: Visual Studio 2019
- **Additional details**: 

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
Hi @jscarano ,

Thanks for reporting this, will get this fixed as soon as possible. Keep the feedback coming!

**Comment by jansenbe** [comment]
This seems to be due to the fact that we always use batching to send requests...in the batch the URL of the site needs to be correct, otherwise there will be an `{"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":{"lang":"en-US","value":"Invalid request."}}}` error.

**Comment by jansenbe** [comment]
Docs are updated to reflect the need to provide url's with the correct case: https://pnp.github.io/pnpcore/articles/consumer/readme.html

**Comment by jansenbe** [comment]
Closing this one: doing this automatically requires an extra roundtrip for each PnPContext object creation, not something that's optimal. For now folks have to provide the correct cased URL as specified in our docs.

**Comment by jpalo** [comment]
What's a link for that doc now? https://pnp.github.io/pnpcore/articles/consumer/readme.html is dead.

**Comment by jansenbe** [comment]
Just https://pnp.github.io/pnpcore/
