### ISSUE TITLE
 Error in Demo.Console\Program.cs:line 106

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/pnpcore#239]
## Category

- [x] Bug

## Describe the bug
Microsoft.Identity.Client.MsalServiceException
  HResult=0x80131500
  Message=A configuration issue is preventing authentication - check the error message from the server for details.
## Steps to reproduce

> entered the required data in appsettings.json 
Ran and logged in but got the error.

## Expected behavior
It should run as is

**Comment by jansenbe** [comment]
Hi @Ofer-Gal , 

There was a small compilation issue in the code: as we're still in preview we sometimes have breaking API changes and in this case the sample was not yet updated. I've just updated the sample for that. Please test with the latest version to see if you still have problems.

Before you can run the sample you need to create an Azure AD application as specified in the readme: https://github.com/pnp/pnpcore/tree/dev/src/samples/Demo.Console, once that's in place authentication should work, but in your case it's not. Can you provide a full stack trace in case you can't get the errors fixed.

**Comment by Ofer-Gal** [comment]
I have an Application regitrated as explain.  
Got me the new Demo.Console and now the error is different. it wants client_secret which is not included in "InteractiveAuthenticationProvider" 
"The request body must contain the following parameter: 'client_assertion' or 'client_secret'."
1. What provider should I use for client secret or certificate?
2. How do I use CredentialManagerAuthenticationProvider? how do I get a name of CredentialManagerAuthenticationProvider ? 
3. Maybe you know where the documentation for "PnP Framework" is? is it the same as https://pnp.github.io/pnpcore/ ?

Thank you much

Error:
________
Microsoft.Identity.Client.MsalServiceException
  HResult=0x80131500
  Message=A configuration issue is preventing authentication - check the error message from the server for details.You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 8414c981-046b-4f8e-9450-ea3460e98300
Correlation ID: 94036a66-5055-4c6c-bede-420eb5e972d0
Timestamp: 2020-11-25 13:42:14Z
  Source=Microsoft.Identity.Client
  StackTrace:
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.<ExecuteRequestAsync>d__11`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.<GetTokenAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.OAuth2.TokenClient.<SendHttpAndClearTelemetryAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Identity.Client.OAuth2.TokenClient.<SendHttpAndClearTelemetryAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.OAuth2.TokenClient.<SendTokenRequestAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<GetTokenResponseAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.<ExecuteAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.<ExecuteAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Auth.InteractiveAuthenticationProvider.<GetAccessTokenAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Auth.InteractiveAuthenticationProvider.<GetAccessTokenAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Auth.InteractiveAuthenticationProvider.<AuthenticateRequestAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Services.BatchClient.<ExecuteSharePointRestBatchAsync>d__46.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Services.BatchClient.<ExecuteBatch>d__37.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.BaseDataModel`1.<BaseGet>d__69.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.BaseDataModel`1.<GetAsyncInternal>d__37.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Model.BaseDataModel`1.<GetAsync>d__33.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Consumer.Program.<Main>d__0.MoveNext() in C:\Users\ogal\source\repos\PnPFrameworkTests\Demo.Console\Program.cs:line 106

  This exception was originally thrown at this call stack:
    [External Code]
    Consumer.Program.Main(string[]) in Program.cs

**Comment by jansenbe** [comment]
Hi @Ofer-Gal ,

Can you cross check below settings in the app you've created in Azure AD. The docs don't mention Access Tokens for the implicit grant, but think that's needed. I'll update the docs based upon your feedback.

![image](https://user-images.githubusercontent.com/7451219/100238413-756dd500-2f30-11eb-8757-b63ce20c9be6.png)

**Comment by Ofer-Gal** [comment]
Yes sir.
I was missing Access tokens and the yes for "Enable the following mobile and desktop flows:"
Now I get another error on line 143 "  await team.PrimaryChannel.GetAsync(p => p.Messages)" But that can be because I do not have any message in the channel.

Thank you much.

Error
-------------------------------------------
"PnP.Core.MicrosoftGraphServiceException
  HResult=0x80131500
  Message=Microsoft Graph service exception"

**Comment by jansenbe** [comment]
Good to hear you've made progress. About the teams, your thinking might be correct, something we'll verify. I'll update the docs to reflect the changes you had to do, thanks for letting us know and testing this library. We plan to go GA in early January, don't hesitate to let the feedback coming.

We'll also be creating more end user documentation, currently we mainly focused on contributor docs.

**Comment by Ofer-Gal** [comment]
Speaking of errors,  await team.PrimaryChannel.GetAsync(p => p.Messages); does not work even when there are messages.
Also, when adding items to the Demo1 list, the .Items.Count() is always 0 and so is Items.Length with graph and itemsQuery 
Knowing Graph, it may be a permission issue.
I tried this sample with .Net 5.0 and it just did not work. no Error.
Shouldn't it work with .NET 5.0? 

Thanks again

**Comment by jansenbe** [comment]
Seems like I was using another app to test this: you indeed need to grant Teams permissions to the Azure AD app and then do the admin consent again. Add [ChannelMessage.Read.All](https://docs.microsoft.com/en-us/graph/api/channel-list-messages?view=graph-rest-1.0&tabs=http) to start with

**Comment by Ofer-Gal** [comment]
After Adding almost all the Graph permissions there are, The console ran everything With .NET 5 Cudus guys!
Can you just explain to me where "PnP.Framework" Version="0.1.57-preview" is fitting? I never found a "Getting Started" for it. Do I need "PnP.Core.Auth" Version="0.3.57-preview3" to use whatever is included in it?
Thanks again

**Comment by jansenbe** [comment]
PnP Framework in a port from our old PnP Sites Core library that only targets SPO as it uses the CSOM for .NET Standard 2.0 framework under the covers. PnP Sites Core will be retired soon, so we'll more forward with PnP Framework and PnP Core SDK. The later is a new, modern and well tested code base whereas PnP Framework is more feature rich. We'll be rebuilding the key features of the PnP Framework library in PnP Core SDK with proper testing and documentation and plug in that PnP Core SDK component in PnP Framework. This will give us a way to step by step upgrade from PnP Framework to PnP Core SDK without impacting our users too much.

PnP Core Auth is our authentication package that depends on PnP Core SDK. You'd typically use both, but there are cases where you don't need PnP Core Auth (e.g. .NET Blazor web assembly) hence it's a separate package.

Since the original issue has been solved I'll close this now.
