### ISSUE TITLE
'Column not found' when adding field to content type

### ISSUE THREAD

**Issue by Maddisan** [pnp/pnpcore#295]
Trying to add an existing column to a content type results in an error. I've tried using default columns and content types as well as new ones.

```cs
await context.Web.GetAsync(p => p.ContentTypes.LoadProperties(p => p.Name, p => p.Description,
                                                        p => p.FieldLinks.LoadProperties(p => p.Name)));
var contentTypes = context.Web.ContentTypes;

var contentType = contentTypes.FirstOrDefault(p => p.Name == "Announcement");

await contentType.FieldLinks.AddAsync("WorkAddress");
```
```
HttpResponseCode: 400
Code: System.ArgumentException
Message: Column 'WorkAddress' does not exist. It may have been deleted by another user. https://example.sharepoint.com/sites/Example
ClientRequestId:

PnP.Core.SharePointRestServiceException: SharePoint Rest service exception
   at PnP.Core.Services.BatchClient.ProcessSharePointRestBatchResponseContent(Batch batch, String batchResponse)
   at PnP.Core.Services.BatchClient.ProcessSharePointRestBatchResponse(SPORestBatch restBatch, String batchResponse)
   at PnP.Core.Services.BatchClient.ExecuteSharePointRestBatchAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Model.BaseDataModel`1.BaseAdd(ApiCall postApiCall, Func`2 fromJsonCasting, Action`1 postMappingJson)
   at PnP.Core.Model.BaseDataModel`1.AddAsync(Dictionary`2 keyValuePairs)
   at PnP.Core.Model.SharePoint.FieldLinkCollection.AddAsync(String fieldInternalName, String displayName, Boolean hidden, Boolean required, Boolean readOnly, Boolean showInDisplayForm)
   at ProjectWorkspacePrototype.Functions.AddColumnTest.Run(HttpRequest request, ILogger log) in ...\Class1.cs:line 38
```

I am able to add columns to content types successfully using Powershell.
` Add-PnPFieldToContentType -Field "WorkAddress" -ContentType "Announcement"`

Any help you can provide on this issue would be much appreciated.

**Comment by jansenbe** [comment]
Thanks for reporting this @Maddisan , this is indeed an issue due to the REST API limitations when working with content types. See https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-visio/jj245869(v=office.15)?redirectedfrom=MSDN#postsyntax.

We'll address this by under the covers either using Graph or hitting the CSOM endpoint (client.svc) and aim to fix this before our GA release latest (planned early February).

See also #266

**Comment by HWHofstee** [comment]
@jansenbe Is there progress (to be expected) on this issue? If not, maybe it is better to remove this option from the documentation or add a comment that this is not working yet.

**Comment by jansenbe** [comment]
@HWHofstee / @Maddisan : apologies this took so long, but proper support for working with field links has been added. See our updated docs: https://pnp.github.io/pnpcore/using-the-sdk/contenttypes-intro.html
