### ISSUE TITLE
PnPContextFactory.CreateAsync - KeyNotFoundException

### ISSUE THREAD

**Issue by dgtheninja** [pnp/pnpcore#395]
## Category

- [x] Bug

## Describe the bug

When trying to create a new PnPContext with the PnPContextFactory using an Azure AD App Identity where I have forgotten to assign permissions properly I get a System.Collections.Generic.KeyNotFoundException with the message "The given key was not present in the dictionary.".

## Steps to reproduce

1. Create an AAD app, with certificate for authentication, but don't assign any permissions
1. Initialise PnP with
`services.AddPnPCore(options =>
            {
                options.PnPContext.GraphFirst = true;
                options.HttpRequests.UserAgent = "ISV|TVPHC|ForceFilesApp";
            });`
1. Try and created new context with `var context = await this.pnpContextFactory.CreateAsync(siteCollectionUri, pnpAuthProvider);`
a. in my case the pnpAuthProvider is a X509CertificateAuthenticationProvider

Here is the stack trace, it looks like it is getting ready to tell me an error occurred but then the error wasn't in the expected format and threw a exception
```
   at System.Text.Json.JsonElement.GetProperty(String propertyName)
   at PnP.Core.SharePointRestError.ParseError(JsonElement error)
   at PnP.Core.SharePointRestError..ctor(ErrorType type, Int32 httpResponseCode, String response)
   at PnP.Core.SharePointRestServiceException..ctor(ErrorType type, Int32 httpResponseCode, String response)
   at PnP.Core.Services.BatchClient.<ExecuteSharePointRestInteractiveAsync>d__48.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at PnP.Core.Services.BatchClient.<ExecuteBatch>d__34.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Model.BaseDataModel`1.<RequestAsync>d__88.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Services.PnPContextFactory.<InitializeContextAsync>d__38.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Services.PnPContextFactory.<CreateAsync>d__33.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SharePointCSOMTrial.Program.<FindNewsArticles2>d__11.MoveNext() in \SharePointCSOMTrial\Program.cs:line 174
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SharePointCSOMTrial.Program.<Main>d__7.MoveNext() in \SharePointCSOMTrial\Program.cs:line 38
```
## Expected behavior

An appropriate error message about lack of permissions, rather than the error about Key Not Found

## Environment details (*development & target environment*)

- **SDK version**: PnP.Framework v1.4.0/ PnP.Core v1.1.0
- **OS**: Windows Server 2016
- **SDK used in**: ASP.Net Web app
- **Framework**: .NET 5
- **Browser(s)**: n/a
- **Tooling**: Visual Studio 2019

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@dgtheninja : it seems to go wrong when we initialize the PnPContext, since the provided token lacks the needed permissions the call fails and somehow the returned error message cannot be deserialized resulting in this error. Thanks for reporting this, providing clear errors is indeed important to speed up troubleshooting.

**Comment by jansenbe** [comment]
https://github.com/pnp/pnpcore/commit/5384e3925989eda73c1c060489b2c61a1a697126 implements a fix. Closing this issue now @dgtheninja .
