### ISSUE TITLE
System.NotSupportedException on IListCollection .Where

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#421]
## Category

- [x] Bug

## Describe the bug
Trying to filter IListCollection with a .Where() clause, I get the following exception:
```
System.NotSupportedException: Constant l is invalid. Only System.Linq.Expressions.ConstantExpression and System.Linq.Expressions.MemberExpression are supported
   at System.Linq.ExpressionExtensions.GetConstantValue(Expression expression)
   at System.Linq.ExpressionExtensions.GetConstantValue(Expression expression)
   at PnP.Core.QueryModel.DataModelQueryTranslator`1.GetFilterValue(Expression expression)
   at PnP.Core.QueryModel.DataModelQueryTranslator`1.AddFilter(BinaryExpression expression)
   at PnP.Core.QueryModel.DataModelQueryTranslator`1.VisitWhere(MethodCallExpression m)
   at PnP.Core.QueryModel.DataModelQueryTranslator`1.VisitMethodCall(MethodCallExpression m)
   at PnP.Core.QueryModel.DataModelQueryTranslator`1.VisitQueryProperties(MethodCallExpression m)
   at PnP.Core.QueryModel.DataModelQueryTranslator`1.VisitMethodCall(MethodCallExpression m)
   at PnP.Core.QueryModel.DataModelQueryTranslator`1.Translate(Expression expression)
   at PnP.Core.QueryModel.DataModelQueryProvider`1.Translate(Expression expression)
   at PnP.Core.QueryModel.DataModelQueryProvider`1.ExecuteObjectAsync(Expression expression, CancellationToken token)
   at PnP.Core.QueryModel.BaseQueryProvider.GetAsyncEnumerable[TResult](Expression expression, CancellationToken token)+MoveNext()
   at PnP.Core.QueryModel.BaseQueryProvider.GetAsyncEnumerable[TResult](Expression expression, CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
```

## Steps to reproduce
``` csharp
var lists = context.Web.Lists.Where(l => !l.NoCrawl && !l.Hidden)
    .QueryProperties(l => l.Id,
                     l => l.Title,
                     l => l.RootFolder.QueryProperties(f => f.Properties, f => f.ServerRelativeUrl));

await foreach (var list in lists.AsAsyncEnumerable())
{
   // Do something
}
```

## Expected behavior
Unless it's just not possible to do more than one condition, I'd expect a Where clause to work almost identically to the old CSOM style.

## Environment details (*development & target environment*)
- **SDK version**: 1.1.0
- **OS**: Windows 10
- **SDK used in**: ASP.Net Web app
- **Framework**: .NET v5.0.5
- **Browser(s)**: N/A
- **Tooling**: Visual Studio 2019

### Additional context

**Comment by DaleyKD** [comment]
Ah, it appears that you have to be verbose with the query.  The following works:
``` csharp
var lists = context.Web.Lists.Where(l => l.NoCrawl == false && l.Hidden == false)
    .QueryProperties(l => l.Id,
                     l => l.Title,
                     l => l.RootFolder.QueryProperties(f => f.Properties, f => f.ServerRelativeUrl));

await foreach (var list in lists.AsAsyncEnumerable())
{
   // Do something
}
```

**Comment by jansenbe** [comment]
@DaleyKD : indeed, we've our own LINQ provider that translates the LINQ expression into a REST/Graph query. It can still use some support for more complex expression handling.
