### ISSUE TITLE
HttpResponseCode: 400 - No retry

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#426]
## Category

- [x] Bug

## Describe the bug
Sometimes, a 400 is thrown by SPO, and no retry is attempted.

```
HttpResponseCode: 400
Code: 
Message: <?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Request Error</title>
    <style>BODY { color: #000000; background-color: white; font-family: Verdana; margin-left: 0px; margin-top: 0px; } #content { margin-left: 30px; font-size: .70em; padding-bottom: 2em; } A:link { color: #336699; font-weight: bold; text-decoration: underline; } A:visited { color: #6699cc; font-weight: bold; text-decoration: underline; } A:active { color: #336699; font-weight: bold; text-decoration: underline; } .heading1 { background-color: #003366; border-bottom: #336699 6px solid; color: #ffffff; font-family: Tahoma; font-size: 26px; font-weight: normal;margin: 0em 0em 10px -20px; padding-bottom: 8px; padding-left: 30px;padding-top: 16px;} pre { font-size:small; background-color: #e5e5cc; padding: 5px; font-family: Courier New; margin-top: 0px; border: 1px #f0f0e0 solid; white-space: pre-wrap; white-space: -pre-wrap; word-wrap: break-word; } table { border-collapse: collapse; border-spacing: 0px; font-family: Verdana;} table th { border-right: 2px white solid; border-bottom: 2px white solid; font-weight: bold; background-color: #cecf9c;} table td { border-right: 2px white solid; border-bottom: 2px white solid; background-color: #e5e5cc;}</style>
  </head>
  <body>
    <div id="content">
      <p class="heading1">Request Error</p>
      <p>The server encountered an error processing the request. See server logs for more details.</p>
    </div>
  </body>
</html>
ClientRequestId: 

PnP.Core.SharePointRestServiceException: SharePoint Rest service exception
   at PnP.Core.Services.BatchClient.ExecuteSharePointRestBatchAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Model.BaseDataModel`1.BaseRetrieveAsync(ApiCall apiOverride, Func`2 fromJsonCasting, Action`1 postMappingJson, Expression`1[] expressions)
   at PnP.Core.Model.SharePoint.Web.GetFileByServerRelativeUrlAsync(String serverRelativeUrl, Expression`1[] expressions)
```

## Steps to reproduce
Can't easily reproduce.  I assume it's good ol' throttling from SPO, and how it seems that it's not always a 429 they send (we've seen others).

I'm iterating 257 list items in a document library, and for each, I have to call `GetFileByServerRelativeUrlAsync` (which I don't love, btw).  I guess by slamming them with such fast requests, they get mad at me.

## Expected behavior
I had hoped PnP would have at least attempted a retry or so, even though it's a 400 (and not a 429).

## Environment details (*development & target environment*)
- **SDK version**: 1.1.0
- **OS**:  Alpine Linux 3.13 (docker image)
- **SDK used in**:  ASP.Net Core Web app
- **Framework**: .NET 5.0.5
- **Tooling**:  Visual Studio 2019

**Comment by jansenbe** [comment]
@DaleyKD : that seems to be the same as this: https://github.com/pnp/pnpframework/issues/292. SharePoint is sometimes returning 400 errors or ssl errors where it shouldn't.

**Comment by DaleyKD** [comment]
@jansenbe - Thanks for the heads up on that.  This definitely lines up with some stuff we've seen in our production code (not even in PnP.Core, just some good ol' fashioned old CSOM code).

**Comment by EinmalIM** [comment]
Microsoft has fixed the issue on May 7th as reported here: https://github.com/SharePoint/sp-dev-docs/issues/6955

We could not find any http 400 failures in our logs after 5/7, so the fix seems to work in our case.
