### ISSUE TITLE
NullReferenceException in Values_CollectionChanged

### ISSUE THREAD

**Issue by DaleyKD** [pnp/pnpcore#447]
## Category

- [x] Bug

## Describe the bug
`NullReferenceException` in `Values_CollectionChanged` event handler.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at PnP.Core.Model.SharePoint.FieldValueCollection.Values_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.InsertItem(Int32 index, T item)
   at PnP.Core.Model.SharePoint.ListDataAsStreamHandler.Deserialize(String json, List list)
   at PnP.Core.Model.SharePoint.List.LoadListDataAsStreamAsync(RenderListDataOptions renderOptions)
   at MyClass() in /src/MyClass.cs:line 198
```

## Steps to reproduce
Not sure what's causing this.  I have no way to replicate it.

## Expected behavior
NullRefs are bad, mkay? :smile:

## Environment details (*development & target environment*)
- **SDK version**: 1.1.41-nightly
- **OS**: Windows 10
- **Framework**: .NET Core v5.0.5
- **Tooling**: Visual Studio 2019

**Comment by DaleyKD** [comment]
Working on a PR right now...

**Comment by DaleyKD** [comment]
Since I'm a goof and don't know how to operate GitHub, this is in the same PR as before... #445 .  Can't figure out how to reverse it.  Will create a new branch for all subsequent PRs.

**Comment by jansenbe** [comment]
It's ok they're combined now, I'll process them together and add two change log entries. Thanks for PR @DaleyKD .

Going forward it's indeed best to create a branch per change that you want to submit as PR. I'll add a new issue to further clarify this in https://pnp.github.io/pnpcore/contributing/setup.html

**Comment by jansenbe** [comment]
@DaleyKD : thanks for your fix, just merged it. Closing this issue now
