### ISSUE TITLE
SaveAsync Null

### ISSUE THREAD

**Issue by quantrpeter** [pnp/pnpcore#451]
Hi
   I got exception when creating a modern page:

```
var web = await context.Web.GetAsync(p=>p.Url, p => p.Title, p => p.Lists, p => p.MasterUrl);
var page = await context.Web.NewPageAsync();
await page.SaveAsync("News.aspx");
await page.PublishAsync();
```

Error:
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'

This exception was originally thrown at this call stack:
    [External Code]
    PeterPnpCore.Program.Main(string[]) in Program.cs

   at PnP.Core.Model.SharePoint.Page.<GetPagesListData>d__94.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.SharePoint.Page.<EnsurePageListItemAsync>d__130.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.SharePoint.Page.<SaveAsync>d__128.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PeterPnpCore.Program.<Main>d__0.MoveNext() in C:\workspace\PeterPnpCore\PeterPnpCore\Program.cs:line 190
```

thanks
Peter

**Comment by jansenbe** [comment]
Hi @quantrpeter ,

I've just tried below in a test case and things just work. I assume the site you're using can work with modern pages? What's the version you're using?

```csharp
[TestMethod]
public async Task Bert()
{
    TestCommon.Instance.Mocking = false;
    using (var context = await TestCommon.Instance.GetContextAsync(TestCommon.TestSite))
    {
        var web = await context.Web.GetAsync(p => p.Url, p => p.Title, p => p.Lists, p => p.MasterUrl);
        var page = await context.Web.NewPageAsync();
        await page.SaveAsync("News.aspx");
        await page.PublishAsync();
    }
}
```

**Comment by jansenbe** [comment]
@quantrpeter : can you provide additional feedback or can we close this issue?

**Comment by jansenbe** [comment]
@quantrpeter : closing this issue...feel free to re-open or create a new one with more details if the problem still persists at your side.
