### ISSUE TITLE
Trouble on setting Note type property.

### ISSUE THREAD

**Issue by gopaldahal** [pnp/pnpcore#525]
## Category

- [x] Bug

## Describe the bug

I am trying to add a field on batch.
Equivalent field detail on List is:
`<Field Type="Note" DisplayName="manage metadata_0" StaticName="ifb8bf8e64a2409792e0bafa62ec7b76" Name="ifb8bf8e64a2409792e0bafa62ec7b76" ID="{f6917801-4617-4a9c-b749-719a0c297056}" ShowInViewForms="FALSE" Required="FALSE" Hidden="TRUE" CanToggleHidden="TRUE" SourceID="{5ef68286-284f-40bf-81dd-05882d3c1481}" ColName="ntext5" RowOrdinal="0" />`

//Code for adding item on batch
```
                Dictionary<string, object> prop1 = new Dictionary<string, object>();
                prop1.Add("Title", "My title 1");
                prop1.Add("ifb8bf8e64a2409792e0bafa62ec7b76", "");
		parentList.Items.AddBatchAsync(prop1, folderRelativePath).Result;
		var batchResponses = context.ExecuteAsync(false).Result;
                foreach (var batchResponse in batchResponses)
                {
                   //here comes with two exception sayng, One or more properties is properly installed
                }
```
				
API BODY
				
```
{
  "listItemCreateInfo": {
    "FolderPath": {
      "DecodedUrl": "/sites/HeyramSite/Lists/HeyramList_1"
    },
    "UnderlyingObjectType": 0
  },
  "bNewDocumentUpdate": false,
  "formValues": [
    {
      "FieldName": "Title",
      "FieldValue": "My title 1"
    },
    {
      "FieldName": "ifb8bf8e64a2409792e0bafa62ec7b76",
      "FieldValue": ""
    }
  ]
}
```

API response

`{"error":{"code":"-2130575340, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"One or more field types are not installed properly. Go to the list settings page to delete these fields."}}}`

## Expected behavior

Item must have been batched committed with out any issue

## Environment details (*development & target environment*)
- **SDK version**: [1.3.0]
- **OS**: [Windows 10 ]
- **SDK used in**: [Console App ]
- **Framework**: [.NET Framework v4.7.2 ]
- **Tooling**: [Visual Studio 2019]

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@gopaldahal : does updating the field outside of a batch work? Did you try with `SystemUpdate` or `UpdateOverwriteVersion` as those fall back to a CSOM request...

**Comment by gopaldahal** [comment]
@jansenbe : Tried with SystemUpdate and UpdateOverwriteVersion. Still no luck.

Exception thrown with message:**One or more field types are not installed properly. Go to the list settings page to delete these fields.**

Stack Trace:
   at PnP.Core.Services.BatchClient.ProcessCsomBatchResponse(CsomBatch csomBatch, String batchResponse, HttpStatusCode statusCode)
   at PnP.Core.Services.BatchClient.<ExecuteCsomBatchAsync>d__53.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PnP.Core.Services.BatchClient.<ExecuteBatch>d__36.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.BaseDataModel`1.<RequestAsync>d__99.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.BaseDataModel`1.<RawRequestAsync>d__102.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.SharePoint.ListItem.<UpdateOverwriteVersionAsync>d__75.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.SharePoint.ListItem.UpdateOverwriteVersion()

**Comment by jansenbe** [comment]
@gopaldahal : since the note field you're trying to set is the hidden field linked to a managed metadata field wouldn't it be better to use the managed metadata field approach instead of trying to force update the note field? See https://pnp.github.io/pnpcore/using-the-sdk/listitems-fields.html#taxonomy-fields for how to do that

**Comment by jansenbe** [comment]
@gopaldahal : also, if you want to clear the field using your above approach try this `prop1.Add("ifb8bf8e64a2409792e0bafa62ec7b76", null);` assuming it's a single value managed metadata field.

**Comment by gopaldahal** [comment]
@jansenbe:
I have no problem with updating the property with   [](https://pnp.github.io/pnpcore/using-the-sdk/listitems-fields.html#taxonomy-fields). But how can I identify that the property is of type managed metadata field, as its showing of Note Type?

**Comment by jansenbe** [comment]
@gopaldahal : SharePoint under the covers creates a hidden Note field for each managed metadata column, e.g.

**Managed Metadata field**
Title: MMSingle
TypeAsString: TaxonomyFieldType
SchemaXml:

```Xml

<Field Type="TaxonomyFieldType" DisplayName="MMSingle" List="{a5fa2a36-9c0a-48c0-a676-729962fdc0d5}" WebId="8c8e101c-1b0d-4253-85e7-c30039bf46e2" ShowField="Term1033" Required="FALSE" EnforceUniqueValues="FALSE" ID="{fda2c9a6-6230-4ad8-9dc2-c56d0a226810}" SourceID="{7d644d41-d86e-4594-99de-479594a68fd9}" StaticName="MMSingle" Name="MMSingle" ColName="int3" RowOrdinal="0" Version="1"><Default /><Customization><ArrayOfProperty><Property><Name>SspId</Name><Value xmlns:q1="http://www.w3.org/2001/XMLSchema" p4:type="q1:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">437b86fc-1258-45a9-85ea-87a29156ce3c</Value></Property><Property><Name>GroupId</Name></Property><Property><Name>TermSetId</Name><Value xmlns:q2="http://www.w3.org/2001/XMLSchema" p4:type="q2:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">93e84384-520f-4531-a756-dbfef49f91bf</Value></Property><Property><Name>AnchorId</Name><Value xmlns:q3="http://www.w3.org/2001/XMLSchema" p4:type="q3:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">00000000-0000-0000-0000-000000000000</Value></Property><Property><Name>UserCreated</Name><Value xmlns:q4="http://www.w3.org/2001/XMLSchema" p4:type="q4:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">false</Value></Property><Property><Name>Open</Name><Value xmlns:q5="http://www.w3.org/2001/XMLSchema" p4:type="q5:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">false</Value></Property><Property><Name>TextField</Name><Value xmlns:q6="http://www.w3.org/2001/XMLSchema" p4:type="q6:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">{c8a3ddee-4c2d-4f0f-974c-615177611e07}</Value></Property><Property><Name>IsPathRendered</Name><Value xmlns:q7="http://www.w3.org/2001/XMLSchema" p4:type="q7:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">false</Value></Property><Property><Name>IsKeyword</Name><Value xmlns:q8="http://www.w3.org/2001/XMLSchema" p4:type="q8:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">false</Value></Property><Property><Name>TargetTemplate</Name></Property><Property><Name>CreateValuesInEditForm</Name><Value xmlns:q9="http://www.w3.org/2001/XMLSchema" p4:type="q9:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">false</Value></Property><Property><Name>FilterAssemblyStrongName</Name><Value xmlns:q10="http://www.w3.org/2001/XMLSchema" p4:type="q10:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">Microsoft.SharePoint.Taxonomy, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c</Value></Property><Property><Name>FilterClassName</Name><Value xmlns:q11="http://www.w3.org/2001/XMLSchema" p4:type="q11:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">Microsoft.SharePoint.Taxonomy.TaxonomyField</Value></Property><Property><Name>FilterMethodName</Name><Value xmlns:q12="http://www.w3.org/2001/XMLSchema" p4:type="q12:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">GetFilteringHtml</Value></Property><Property><Name>FilterJavascriptProperty</Name><Value xmlns:q13="http://www.w3.org/2001/XMLSchema" p4:type="q13:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">FilteringJavascript</Value></Property></ArrayOfProperty></Customization></Field>
```

Linked hidden note field:
Title: MMSingle_0
TypeAsString: Note
SchemaXml:

```Xml
<Field Type="Note" DisplayName="MMSingle_0" StaticName="fda2c9a662304ad89dc2c56d0a226810" Name="fda2c9a662304ad89dc2c56d0a226810" ID="{c8a3ddee-4c2d-4f0f-974c-615177611e07}" ShowInViewForms="FALSE" Required="FALSE" Hidden="TRUE" CanToggleHidden="TRUE" SourceID="{7d644d41-d86e-4594-99de-479594a68fd9}" ColName="ntext2" RowOrdinal="0" />
```

The name of the Note field is actually the ID of the corresponding taxonomy field, so when you encounter hidden note fields you  could check if they belong to an taxonomy field.

That being said, did you try actually writing content to the note field (so not setting to empty or null)?

**Comment by gopaldahal** [comment]
@jansenbe: I tried with empty, null, and with a random string, wasn't working on my end.
