### ISSUE TITLE
Unhandled exception thrown while making request with LoadListDataAsStreamAsync. Problem with 1.3.0

### ISSUE THREAD

**Issue by gopaldahal** [pnp/pnpcore#528]
## Category

- [x] Bug

## Describe the bug

Having an issue with making requests for list items with the LoadListDataAsStreamAsync method.
The issue is only on 1.3.0 version. Working as expected on 1.2.0.
The problem is only in some libraries.

```
              // the fields are all the fields of selected list
               var viewXml = "<View><ViewFields><FieldRef Name='ContentTypeId'/><FieldRef Name='Title'/><FieldRef Name='_ModerationComments'/><FieldRef Name='File_x0020_Type'/><FieldRef Name='ComplianceAssetId'/><FieldRef Name='PeopleAndGroup'/><FieldRef Name='MultiChoice'/><FieldRef Name='HyperLink'/><FieldRef Name='Number'/><FieldRef Name='DateTime'/><FieldRef Name='chkBox'/><FieldRef Name='multiline'/><FieldRef Name='manage_x0020_metadata'/><FieldRef Name='ifb8bf8e64a2409792e0bafa62ec7b76'/><FieldRef Name='TaxCatchAll'/><FieldRef Name='selflookup'/><FieldRef Name='selflookup_x003a_Title'/><FieldRef Name='HeyramTerm'/><FieldRef Name='l8f2c71915d94c09b281215aff4d3f7e'/><FieldRef Name='ID'/><FieldRef Name='ContentType'/><FieldRef Name='Modified'/><FieldRef Name='Created'/><FieldRef Name='Author'/><FieldRef Name='Editor'/><FieldRef Name='_HasCopyDestinations'/><FieldRef Name='_CopySource'/><FieldRef Name='owshiddenversion'/><FieldRef Name='WorkflowVersion'/><FieldRef Name='_UIVersion'/><FieldRef Name='_UIVersionString'/><FieldRef Name='Attachments'/><FieldRef Name='_ModerationStatus'/><FieldRef Name='Edit'/><FieldRef Name='LinkTitleNoMenu'/><FieldRef Name='LinkTitle'/><FieldRef Name='LinkTitle2'/><FieldRef Name='SelectTitle'/><FieldRef Name='InstanceID'/><FieldRef Name='Order'/><FieldRef Name='GUID'/><FieldRef Name='WorkflowInstanceID'/><FieldRef Name='FileRef'/><FieldRef Name='FileDirRef'/><FieldRef Name='Last_x0020_Modified'/><FieldRef Name='Created_x0020_Date'/><FieldRef Name='FSObjType'/><FieldRef Name='SortBehavior'/><FieldRef Name='PermMask'/><FieldRef Name='PrincipalCount'/><FieldRef Name='FileLeafRef'/><FieldRef Name='UniqueId'/><FieldRef Name='SyncClientId'/><FieldRef Name='ProgId'/><FieldRef Name='ScopeId'/><FieldRef Name='HTML_x0020_File_x0020_Type'/><FieldRef Name='_EditMenuTableStart'/><FieldRef Name='_EditMenuTableStart2'/><FieldRef Name='_EditMenuTableEnd'/><FieldRef Name='LinkFilenameNoMenu'/><FieldRef Name='LinkFilename'/><FieldRef Name='LinkFilename2'/><FieldRef Name='DocIcon'/><FieldRef Name='ServerUrl'/><FieldRef Name='EncodedAbsUrl'/><FieldRef Name='BaseName'/><FieldRef Name='MetaInfo'/><FieldRef Name='_Level'/><FieldRef Name='_IsCurrentVersion'/><FieldRef Name='ItemChildCount'/><FieldRef Name='FolderChildCount'/><FieldRef Name='Restricted'/><FieldRef Name='OriginatorId'/><FieldRef Name='NoExecute'/><FieldRef Name='ContentVersion'/><FieldRef Name='_ComplianceFlags'/><FieldRef Name='_ComplianceTag'/><FieldRef Name='_ComplianceTagWrittenTime'/><FieldRef Name='_ComplianceTagUserId'/><FieldRef Name='_IsRecord'/><FieldRef Name='AccessPolicy'/><FieldRef Name='_VirusStatus'/><FieldRef Name='_VirusVendorID'/><FieldRef Name='_VirusInfo'/><FieldRef Name='AppAuthor'/><FieldRef Name='AppEditor'/><FieldRef Name='SMTotalSize'/><FieldRef Name='SMLastModifiedDate'/><FieldRef Name='SMTotalFileStreamSize'/><FieldRef Name='SMTotalFileCount'/><FieldRef Name='_CommentFlags'/><FieldRef Name='_CommentCount'/></ViewFields><RowLimit Paged='TRUE'>200</RowLimit></View>"
                var loadOption = new RenderListDataOptions()
                {
                    ViewXml = viewXml,
                    RenderOptions = RenderListDataOptionsFlags.ListData,
                    Paging = nextPage ?? null,
                    DatesInUtc = true,
                    FolderServerRelativeUrl = folderRelativeUrl
                };
                while (paging)
                {
                    var output = parentList.LoadListDataAsStreamAsync(loadOption).Result;

                    if (output.ContainsKey("NextHref"))
                    {
                        nextPage = output["NextHref"].ToString().Substring(1);
                    }
                    else
                    {
                        paging = false;
                    }
                }
```

Exception thrown under given stack trace with msg "Object reference not set to an instance of an object."
   at PnP.Core.Model.SharePoint.FieldValueCollection.Commit()
   at PnP.Core.Model.TransientDictionary.Commit()
   at PnP.Core.Model.SharePoint.ListDataAsStreamHandler.<Deserialize>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PnP.Core.Model.SharePoint.List.<LoadListDataAsStreamAsync>d__155.MoveNext()

## Steps to reproduce
Code shared on Description

## Expected behavior

Methos must give result with out error

## Environment details (*development & target environment*)
- **SDK version**: [1.3.0 ]
- **OS**: [Windows 10]
- **SDK used in**: [Console App ]
- **Framework**: [.NET Framework v4.7.2 ]
- **Tooling**: [ Visual Studio 2019]

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
I've added some extra safety checks on null and types, let me know if that helps (will be available in the next nightly release).

**Comment by gopaldahal** [comment]
> I've added some extra safety checks on null and types, let me know if that helps (will be available in the next nightly release) @gopaldahal

Will update you, if its resolved.

**Comment by gopaldahal** [comment]
@jansenbe:
It is fine now. Thank you.
