### ISSUE TITLE
Error attempting to get web.webs

### ISSUE THREAD

**Issue by juliemturner** [pnp/pnpcore#531]
## Category

- [x] Bug

## Describe the bug

I have a solution that is executing various calls for list information in the root web.  I then want to verify that there are no similar document libraries (all these calls seem to be working fine) in any potential sub webs (as this is a migration situation) and so after retireving library information I am attempting to get a listing of any subwebs in a web.  

I have tried:

`var webs = await pnpContext.Web.Webs.ToListAsync();`
and
`var webs = await pnpContext.Web.Webs.QueryProperties(p => p.Id).ToListAsync();`

Both throw the error: 

**Specify the GraphGet/GraphGetLinq field of the ClassMapping property** -    
at PnP.Core.Services.QueryClient.BuildGetAPICallGraphAsync[TModel](BaseDataModel`1 model, EntityInfo entity, ODataQuery`1 oDataQuery, ApiCall apiOverride, Boolean useLinqGet, Boolean loadPages) 
at PnP.Core.Services.QueryClient.BuildGetAPICallAsync[TModel](BaseDataModel`1 model, EntityInfo entity, ODataQuery`1 oDataQuery, ApiCall apiOverride, Boolean forceSPORest, Boolean useLinqGet, Boolean loadPages)
at PnP.Core.QueryModel.DataModelQueryService`1.AddToBatchAsync(ODataQuery`1 query, Batch batch)
at PnP.Core.QueryModel.DataModelQueryService`1.ExecuteQueryAsync(Type expressionType, ODataQuery`1 query, CancellationToken token)
at PnP.Core.QueryModel.BaseQueryProvider.GetAsyncEnumerable[TResult](Expression expression, CancellationToken token)+MoveNext()
[2021-08-27T19:32:02.333Z]    at PnP.Core.QueryModel.BaseQueryProvider.GetAsyncEnumerable[TResult](Expression expression, CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
[2021-08-27T19:32:02.335Z]    at PnP.Core.QueryModel.QueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
[2021-08-27T19:32:02.338Z]    at PnP.Core.QueryModel.QueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)

## Steps to reproduce

The calls are outlined above but for all intents and purposes they are simply wrapped in a pnpContext using...

using (var pnpContext = await pnpContextFactory.CreateAsync(new Uri(siteUrl)))
{
     >>>> My Code
}

## Expected behavior

Not sure what is wrong with my format that it's throwing this error

## Environment details (*development & target environment*)

- **SDK version**: PnP.Core.Auth -> 1.3.0
- **OS**: Windows 10
- **SDK used in**: Azure Function - Local Debugging
- **Framework**: .NET Core v3.1
- **Tooling**: Visual Studio 2019

**Comment by juliemturner** [comment]
Yes, thank you... I don't know why I'm struggling with the documentation so much... I search for things but apparently never ask the questions correctly.  Appreciate the assist.
