### ISSUE TITLE
Timezone Information is not working

### ISSUE THREAD

**Issue by henningeiben** [pnp/pnpcore#543]
## Category

- [x] Bug

## Describe the bug

I'm trying to add a new listitem using the PnP-SDK which contains a DateTime-field. Since me SharePoint site is based on "German" I get:

```
[2021-09-13T08:56:48.777Z]  ---> System.ArgumentException: Unknown timezone mapping
[2021-09-13T08:56:48.777Z]    at PnP.Core.Model.SharePoint.TimeZone.GetTimeZoneInfoFromSharePoint(String timeZoneDescription)
[2021-09-13T08:56:48.778Z]    at PnP.Core.Model.SharePoint.TimeZone.UtcDelta(DateTime dateTime)
[2021-09-13T08:56:48.779Z]    at PnP.Core.Model.SharePoint.TimeZone.UtcToLocalTime(DateTime dateTime)
[2021-09-13T08:56:48.780Z]    at PnP.Core.Model.SharePoint.ListItem.DateTimeToSharePointWebDateTimeString(PnPContext context, DateTime input)
[2021-09-13T08:56:48.780Z]    at PnP.Core.Model.SharePoint.ListItem.BuildValidateUpdateItemPayload(PnPContext context, KeyValuePair`2 changedProp, Object field)
[2021-09-13T08:56:48.781Z]    at PnP.Core.Model.SharePoint.ListItem.<.ctor>b__2_2(Dictionary`2 keyValuePairs)
[2021-09-13T08:56:48.782Z]    at PnP.Core.Model.BaseDataModel`1.AddBatchAsync(Batch batch, Dictionary`2 keyValuePairs)
[2021-09-13T08:56:48.783Z]    at PnP.Core.Model.SharePoint.ListItemCollection.AddBatchAsync(Batch batch, Dictionary`2 values, String folderPath, FileSystemObjectType fileSystemObjectType)
[2021-09-13T08:56:48.784Z]    at MyFunction.Function1.Run(String myBlob, String name, FunctionContext context) in C:\projects\playground\MyFunction\Function1.cs:line 119
[2021-09-13T08:56:48.785Z]    at Microsoft.Azure.Functions.Worker.Invocation.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\VoidTaskMethodInvoker.cs:line 22
[2021-09-13T08:56:48.785Z]    --- End of inner exception stack trace ---
```

I looked at the code and found, that [GetTimeZoneInfoFromSharePoint](https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core/Model/SharePoint/Core/Internal/TimeZone.cs#L55) is only looking for english timezones. But instead of "(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna" SharePoint is returning "(UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien" instead.

## Expected behavior

The timezone detection should work independed of language settings.

## Environment details (*development & target environment*)

- **SDK version**: 1.3.0
- **OS**: Windows 10
- **SDK used in**: Azure Function (c#)
- **Framework**: dotnet 5.0
- **Tooling**: Visual Studio 2019

**Comment by henningeiben** [comment]
Sure - will do!

**Comment by henningeiben** [comment]
@jansenbe: works like a charm - at least for a german-based site-collection! 😁
