### ISSUE TITLE
SetComplianceTag throws "Invalid field name. {f4ebd738-21db-4797-9229-2e817dd2367d} 

### ISSUE THREAD

**Issue by varunssis** [pnp/pnpcore#560]
## Category

- [x] Bug

## Describe the bug
When using and method for object of type -  {PnP.Core.Model.SharePoint.ListItem}.SetComplianceTag("RetainFor2DaysFromLabelled
", false, false, false, false);
In certain occasions I receive the following exception:
{HttpResponseCode: 400Code: System.ArgumentExceptionMessage: Invalid field name. {f4ebd738-21db-4797-9229-2e817dd2367d}  /sites/Dev/Test2ClientRequestId: }

See exception details below in Additional context.

![label](https://user-images.githubusercontent.com/91848895/135769469-14378bc7-668f-4044-8944-3af679b7a5bf.png)

## Steps to reproduce

1. In my Azure Function, I am trying to set the compliance tag for an SharePoint document using the SetComplianceTag method
2. I am able to get this to work for some times, but randomly the method fails with the errors described above. Upon googling, it seems that this field associated with the GUID is TagEventDate
3. It seems the retention label is set, but an exception is thrown in code at this line
4. See attached image to confirm that the ListItem is valid and also the screenshot of the SharePoint List with the label applied

## Expected behavior

Able to set the retention label for the list item correctly, without an exception being thrown.

## Environment details (*development & target environment*)

- PnP Core 1.3
- PnP Framework 1.6
- .Net Core 3.1
- OS Windows server 2016 (VM)
- Visual studio 2019 16.10.2

### Additional context (stack trace)
![object](https://user-images.githubusercontent.com/91848895/135769226-ee42d521-82be-4dac-a7a3-85c7a83d89ee.png)

   at PnP.Core.Services.BatchClient.ProcessSharePointRestBatchResponseContent(Batch batch, String batchResponse)
   at PnP.Core.Services.BatchClient.<ProcessSharePointRestBatchResponse>d__48.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at PnP.Core.Services.BatchClient.<ExecuteSharePointRestBatchAsync>d__46.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at PnP.Core.Services.BatchClient.<ExecuteBatch>d__36.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Model.BaseDataModel`1.<RequestAsync>d__99.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Model.BaseDataModel`1.<RawRequestAsync>d__102.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Model.SharePoint.ListItem.<SetComplianceTagAsync>d__94.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PnP.Core.Model.SharePoint.ListItem.SetComplianceTag(String complianceTag, Boolean isTagPolicyHold, Boolean isTagPolicyRecord, Boolean isEventBasedTag, Boolean isTagSuperLock)
   at XXXXX.XXXX.XXXXXX.XXXX.SPHelper.ProcessItem(ILogger log, Site s, String webUrl, PnPContext ctx, DocumentChange change) in F:\XXXXX\XXXX\XXX\XXX.XXX.XXXXXX\\Helpers\SPHelper.cs:line 127
   at XX.XX.XXX.XXX.XX.GetItemChangesFn.GetSPListItemChangeLog(List list, ILogger log) in XXXXX\GetItemChangesFn.cs:line 88
   at xxxx.GetItemChangesFn.<>c__DisplayClass6_0.<Run>b__0(List lst) in XXXXXXX\GetItemChangesFn.cs:line 38
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at xxxx.GetItemChangesFn.Run(TimerInfo myTimer, ILogger log) in XXXXXXXXX\GetItemChangesFn.cs:line 36
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidMethodInvoker.cs:line 21
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.<InvokeAsync>d__10.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@varunssis : I've been testing with compliance tags today and so far did not notice this issue. Do you still see this problem? When the API complains about the missing field, did you verify the field in question was missing?

**Comment by jansenbe** [comment]
Did some more research and the missing field is an OOB field that should be present. If this issue stays please open a ticket with Microsoft support to further research this. As we're just calling the provided API without any specific logic there's nothing we can do about this issue from within the scope of the PnP Core SDK open source project. Thanks for your understanding.
