### ISSUE TITLE
SharePoint Rest service exception produced when trying to create new website

### ISSUE THREAD

**Issue by indieza** [pnp/pnpcore#635]
## Category

- [x] Bug

## Describe the issue

If I have an input model for SharePoint website, Title, Description, URL, Template Type and Language and try to create a new SharePoint website with the following logic I get the target error message.

Code
```
public async Task<string> CreateWeb(IWeb web, WebsiteInputModel model)
{
    var newWeb = await web.Webs.AddAsync(new WebOptions
    {
        Title = model.Title,
        Description = model.Description,
        Url = model.Url,
        Language = model.Language,
        Template = model.Template,
    }).ConfigureAwait(false);

    return newWeb.Url.AbsoluteUri;
}
```

Message - "SharePoint Rest service exception"
```
PnP.Core.Services.BatchClient.ProcessSharePointRestBatchResponseContent(Batch batch, String batchResponse)
at PnP.Core.Services.BatchClient.<ProcessSharePointRestBatchResponse>d__48.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at PnP.Core.Services.BatchClient.<ExecuteSharePointRestBatchAsync>d__46.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at PnP.Core.Services.BatchClient.<ExecuteBatch>d__36.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at PnP.Core.Model.BaseDataModel`1.<BaseAdd>d__73.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at PnP.Core.Model.BaseDataModel`1.<AddAsync>d__34.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at PnP.Core.Model.SharePoint.WebCollection.<AddAsync>d__2.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
```

## Expected behavior

In the following case I want to give a chance to a target user to create a SharePoint website from C# WinForms Application

Regards,
Simeon Valev

**Comment by jansenbe** [comment]
@indieza : adding a sub web is something we do in many unit tests, so this should work. Here's our docs: https://pnp.github.io/pnpcore/using-the-sdk/webs-intro.html#adding-a-web

I think you're somehow passing in bad input data, maybe try with my sample and add additional properties one by one to validate them. 

Also when catching a PnP Core SDK exception call `.ToString()` on the exception as that will provide the actual REST error.

**Comment by indieza** [comment]
Is it possible to be that I am not an administrator? I receive the following error?.
```
HttpResponseCode: 403
Code: System.UnauthorizedAccessException
Message: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
ClientRequestId: 
```

**Comment by jansenbe** [comment]
You need to be a site collection admin of the site you're adding a web to

**Comment by indieza** [comment]
Yes, this is the problem. Thank you very much. I will close the issue

Regards,
Simeon Valev
