### ISSUE TITLE
Problem with RoleAssignments when encountering 'Limited Access System Group For List'

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/pnpcore#720]
## Category

- [x] Bug

## Describe the bug
```

await o.LoadAsync(w => w.RoleAssignments);

foreach (var ra in o.RoleAssignments.ToList())
{
 //Expodes on .ToList().
}

```

Exception details:

```
(ERROR)   Failed to enumerate role assigments.
(EXCEPTION)   SharePoint Rest service exception -(
HttpResponseCode: 404
Code: System.ArgumentException
Message: Can not find the principal with id: 19.
ClientRequestId: [redacted]
SPClientServiceRequestDuration: 73
X-SharePointHealthScore: 1
X-SP-SERVERSTATE: ReadOnly=0
CONTENT-TYPE: application/json;odata=verbose;charset=utf-8
: 

PnP.Core.SharePointRestServiceException: SharePoint Rest service exception
   at PnP.Core.Services.BatchClient.ProcessSharePointRestBatchResponseContent(Batch batch, String batchResponse, HttpResponseHeaders headers) in C:\GIT\pnpcore\src\sdk\PnP.Core\Services\Core\BatchClient.cs:line 1304
   at PnP.Core.Services.BatchClient.<ProcessSharePointRestBatchResponse>d__55.MoveNext() in C:\GIT\pnpcore\src\sdk\PnP.Core\Services\Core\BatchClient.cs:line 1242
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Services.BatchClient.<ExecuteSharePointRestBatchAsync>d__53.MoveNext() in C:\GIT\pnpcore\src\sdk\PnP.Core\Services\Core\BatchClient.cs:line 1062
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Services.BatchClient.<ExecuteBatch>d__41.MoveNext() in C:\GIT\pnpcore\src\sdk\PnP.Core\Services\Core\BatchClient.cs:line 340
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.Services.PnPContext.<ExecuteAsync>d__102.MoveNext() in C:\GIT\pnpcore\src\sdk\PnP.Core\Services\Core\PnPContext.cs:line 374
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PnP.Core.QueryModel.DataModelQueryService`1.<ExecuteQueryAsync>d__16.MoveNext() in C:\GIT\pnpcore\src\sdk\PnP.Core\QueryModel\Query\DataModelQueryService.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PnP.Core.QueryModel.BaseQueryProvider.Execute(Expression expression) in C:\GIT\pnpcore\src\sdk\PnP.Core\QueryModel\Linq\BaseQueryProvider.cs:line 142
   at PnP.Core.QueryModel.BaseQueryableDataModelCollection`1.GetEnumerator() in C:\GIT\pnpcore\src\sdk\PnP.Core\QueryModel\Model\BaseQueryableDataModelCollection.cs:line 47
```

This occurs on a new publishing communications site (O365), the Documents library, and likely a document within the library was shared with a permission-granting sharing link which another user clicked into granting temporary hidden permissions.  In the UI you only see the 3 default site permission groups.

When you go to:
https://CONTOSO.sharepoint.com/teams/PublishingSite/_api/web/lists/getbytitle('Documents')/roleassignments
(SP Rest API to get RoleAssignments on the list)

You do not receive an error, and you do receive the following XML:

```
<?xml version="1.0" encoding="utf-8"?>
<feed xml:base="https://CONTOSO.sharepoint.com/teams/PublishingSite/_api/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml">
	<id>9c5086e0-83d7-49db-ab9c-affaabbfef48</id>
	<title />
	<updated>2022-01-11T23:36:35Z</updated>
	<entry>
		<id>https://CONTOSO.sharepoint.com/teams/PublishingSite/_api/Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(3)</id>
		<category term="SP.RoleAssignment" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
		<link rel="edit" href="Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(3)" />
		<link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/Member" type="application/atom+xml;type=entry" title="Member" href="Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(3)/Member" />
		<link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/RoleDefinitionBindings" type="application/atom+xml;type=feed" title="RoleDefinitionBindings" href="Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(3)/RoleDefinitionBindings" />
		<title />
		<updated>2022-01-11T23:36:35Z</updated>
		<author>
			<name />
		</author>
		<content type="application/xml">
			<m:properties>
				<d:PrincipalId m:type="Edm.Int32">3</d:PrincipalId>
			</m:properties>
		</content>
	</entry>
	<entry>
		<id>https://CONTOSO.sharepoint.com/teams/PublishingSite/_api/Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(4)</id>
		<category term="SP.RoleAssignment" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
		<link rel="edit" href="Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(4)" />
		<link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/Member" type="application/atom+xml;type=entry" title="Member" href="Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(4)/Member" />
		<link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/RoleDefinitionBindings" type="application/atom+xml;type=feed" title="RoleDefinitionBindings" href="Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(4)/RoleDefinitionBindings" />
		<title />
		<updated>2022-01-11T23:36:35Z</updated>
		<author>
			<name />
		</author>
		<content type="application/xml">
			<m:properties>
				<d:PrincipalId m:type="Edm.Int32">4</d:PrincipalId>
			</m:properties>
		</content>
	</entry>
	<entry>
		<id>https://CONTOSO.sharepoint.com/teams/PublishingSite/_api/Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(5)</id>
		<category term="SP.RoleAssignment" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
		<link rel="edit" href="Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(5)" />
		<link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/Member" type="application/atom+xml;type=entry" title="Member" href="Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(5)/Member" />
		<link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/RoleDefinitionBindings" type="application/atom+xml;type=feed" title="RoleDefinitionBindings" href="Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(5)/RoleDefinitionBindings" />
		<title />
		<updated>2022-01-11T23:36:35Z</updated>
		<author>
			<name />
		</author>
		<content type="application/xml">
			<m:properties>
				<d:PrincipalId m:type="Edm.Int32">5</d:PrincipalId>
			</m:properties>
		</content>
	</entry>
	<entry>
		<id>https://CONTOSO.sharepoint.com/teams/PublishingSite/_api/Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(19)</id>
		<category term="SP.RoleAssignment" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
		<link rel="edit" href="Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(19)" />
		<link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/Member" type="application/atom+xml;type=entry" title="Member" href="Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(19)/Member" />
		<link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/RoleDefinitionBindings" type="application/atom+xml;type=feed" title="RoleDefinitionBindings" href="Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(19)/RoleDefinitionBindings" />
		<title />
		<updated>2022-01-11T23:36:35Z</updated>
		<author>
			<name />
		</author>
		<content type="application/xml">
			<m:properties>
				<d:PrincipalId m:type="Edm.Int32">19</d:PrincipalId>
			</m:properties>
		</content>
	</entry>
</feed>
```

Which does contain a principal id of 19, the link:
https://CONTOSO.sharepoint.com/teams/PublishingSite/_api/Web/Lists(guid'eabb1cc2-016d-530c-9d8c-2d4817ad6027')/RoleAssignments/GetByPrincipalId(19)/Member

Returns:
```
<?xml version="1.0" encoding="utf-8"?>
<entry xml:base="https://CONTOSO.sharepoint.com/teams/PublishingSite/_api/" xmlns="http://www.w3.org/2005/Atom" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns:georss="http://www.georss.org/georss" xmlns:gml="http://www.opengis.net/gml">
	<id>https://CONTOSO.sharepoint.com/teams/PublishingSite/_api/Web/SiteGroups/GetById(19)</id>
	<category term="SP.Group" scheme="http://schemas.microsoft.com/ado/2007/08/dataservices/scheme" />
	<link rel="edit" href="Web/SiteGroups/GetById(19)" />
	<link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/Owner" type="application/atom+xml;type=entry" title="Owner" href="Web/SiteGroups/GetById(19)/Owner" />
	<link rel="http://schemas.microsoft.com/ado/2007/08/dataservices/related/Users" type="application/atom+xml;type=feed" title="Users" href="Web/SiteGroups/GetById(19)/Users" />
	<title />
	<updated>2022-01-11T23:38:31Z</updated>
	<author>
		<name />
	</author>
	<content type="application/xml">
		<m:properties>
			<d:Id m:type="Edm.Int32">19</d:Id>
			<d:IsHiddenInUI m:type="Edm.Boolean">false</d:IsHiddenInUI>
			<d:LoginName>Limited Access System Group For List eabb1cc2-016d-530c-9d8c-2d4817ad6027</d:LoginName>
			<d:Title>Limited Access System Group For List eabb1cc2-016d-530c-9d8c-2d4817ad6027</d:Title>
			<d:PrincipalType m:type="Edm.Int32">8</d:PrincipalType>
			<d:AllowMembersEditMembership m:type="Edm.Boolean">false</d:AllowMembersEditMembership>
			<d:AllowRequestToJoinLeave m:type="Edm.Boolean">false</d:AllowRequestToJoinLeave>
			<d:AutoAcceptRequestToJoinLeave m:type="Edm.Boolean">false</d:AutoAcceptRequestToJoinLeave>
			<d:Description>Limited Access System Group For List eabb1cc2-016d-530c-9d8c-2d4817ad6027</d:Description>
			<d:OnlyAllowMembersViewMembership m:type="Edm.Boolean">true</d:OnlyAllowMembersViewMembership>
			<d:OwnerTitle>System Account</d:OwnerTitle>
			<d:RequestToJoinLeaveEmailSetting m:null="true" />
		</m:properties>
	</content>
</entry>
```

So the REST API return no error when calling for the details but PNP throws an exception saying principal id 19 cannot be found.

These were queried with the same account that the code was authenticated as.

## Steps to reproduce

See above, likely related to having a permission granting sharing link and somehow the query failing to expand it?

## Expected behavior

No exception, receive the list role assignment without issue as the rest api isn't throwing an exception.

## Environment details (*development & target environment*)

- **SDK version**: 1.4.5
- **OS**: Win10
- **SDK used in**: .NET 4.7
- **Framework**: .NET 4.7
- **Browser(s)**: na
- **Tooling**: VS 2019
- **Additional details**: 

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@SPDEVGUY : so you're not seeing this issue on all communication sites? 

Since you already load the role assignments in the first step maybe test with this code:

```csharp

await o.LoadAsync(w => w.RoleAssignments);

foreach (var ra in o.RoleAssignments.AsRequested())
{

}
```

**Comment by jansenbe** [comment]
@SPDEVGUY : do you have an update on my questions?

**Comment by SPDEVGUY** [comment]
I'll narrow down the code and provide an update tomorrow, apologies for the delay

Kevin Cole | SharePoint MCM
780.271.2171
________________________________

**Comment by SPDEVGUY** [comment]
I've narrowed down the code, and it still occurs with AsRequested.

```
public static async Task<bool> LoadSite(string url, Func<ISite,Task> useIt)
        {
            PnPContext ctx=null;
            try
            {
                ctx = await Pnp.CreateAsync(new Uri(url));
                if (ctx == null) return false;

                await useIt(ctx.Site);
                return true;
            } finally
            {
                if (ctx != null) ctx.Dispose();
            }
        }

 static async Task DirectTest()
        {
            try
            {
                using (var auth = new PnpAuth())
                {
                    await auth.Start();

                    var exists = await PnpAuth.LoadSite($"https://CONTOSO.sharepoint.com/teams/CommunicationSite", async (site) =>
                    {
                        var rootweb = site.RootWeb;

                            var list = rootweb.Lists.GetById(new Guid("eabb1cc2-016d-530c-9d8c-2d4817ad6027"));
                            await list.LoadAsync(p => p.RoleAssignments);

                            foreach (var ra in list.RoleAssignments.AsRequested())
                            {
                                Console.WriteLine(ra.PrincipalId);

                                //Exception occurs here once it reaches Assignment ID 19.
                                foreach (var rd in ra.RoleDefinitions)
                                {
                                    Console.WriteLine($"\t{rd.Id}");
                                }
                            }
                    });
                }
            } catch(Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
```

**Comment by jansenbe** [comment]
@SPDEVGUY : Would recommend using below construct and see if that works better. This code does request role assignments and their respective role definitions in one go. If there are no role definitions then the code should not fail.

```csharp
await list.LoadAsync(w => w.RoleAssignments.QueryProperties(p => p.RoleDefinitions), w => w.HasUniqueRoleAssignments);

foreach (var ra in list.RoleAssignments.AsRequested())
{
    Console.WriteLine(ra.PrincipalId);

    foreach (var rd in ra.RoleDefinitions.AsRequested())
    {
        Console.WriteLine($"\t{rd.Id}");
    }
}
```

**Comment by SPDEVGUY** [comment]
That works!  Likely need to add some logic to handle the failure on the other way then as a code fix for pnp.
