### ISSUE TITLE
Adding Team to Team Site does not handle retries as expected

### ISSUE THREAD

**Issue by mortenostigard** [pnp/pnpcore#886]
## Category

- [x] Bug

## Describe the bug

When creating a Team for a Microsoft 365 Group connected site using
`var contextWithTeam = await context.GetTeamManager().CreateTeamAsync(
    new TeamForGroupOptions(groupId))` it seems as if the implementation does not handle retries as intended (I did not override the default `TeamCreationOptions`).

It quite often throws a `MicrosoftGraphServiceException` saying "No team was found with group id '<whatever guid>'".

Looking at the stack trace and implementation it might seem like retries are handled well for the PUT operation, but not for the consecutive GET operation occurring in `PnP.Core.Admin.Model.Teams.TeamCreator.GetPnPContextWithTeamAsync(PnPContext context, Guid groupId)` when trying to load the Team into the Context.

The Team is still provisioned correctly, which further strengthens the suspicion.

**Stack trace:**
HttpResponseCode: 404
[2022-06-20T18:13:36.576Z] Code: NotFound
[2022-06-20T18:13:36.580Z] Message: No team found with Group Id 1eda04b4-5c21-472b-b038-d4da61ed1c7a
[2022-06-20T18:13:36.582Z] ClientRequestId: 1683671b-5448-43bc-8fce-f7f7fb880bda
[2022-06-20T18:13:36.583Z] message: No team found with Group Id 1eda04b4-5c21-472b-b038-d4da61ed1c7a
[2022-06-20T18:13:36.585Z] code: ItemNotFound
[2022-06-20T18:13:36.587Z] innerError: {}
[2022-06-20T18:13:36.589Z] date: 2022-06-20T18:10:02
[2022-06-20T18:13:36.590Z] client-request-id: 1683671b-5448-43bc-8fce-f7f7fb880bda
[2022-06-20T18:13:36.592Z]
[2022-06-20T18:13:36.594Z] PnP.Core.MicrosoftGraphServiceException: Microsoft Graph service exception
[2022-06-20T18:13:36.598Z]    at PnP.Core.Services.BatchClient.ExecuteMicrosoftGraphInteractiveAsync(Batch batch)
[2022-06-20T18:13:36.600Z]    at PnP.Core.Services.BatchClient.ExecuteMicrosoftGraphBatchAsync(Batch batch)
[2022-06-20T18:13:36.602Z]    at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
[2022-06-20T18:13:36.604Z]    at PnP.Core.Model.BaseDataModel`1.BaseRetrieveAsync(ApiCall apiOverride, Func`2 fromJsonCasting, Action`1 postMappingJson, Expression`1[] expressions)
[2022-06-20T18:13:36.608Z]    at PnP.Core.Admin.Model.Teams.TeamCreator.GetPnPContextWithTeamAsync(PnPContext context, Guid groupId)
[2022-06-20T18:13:36.617Z]    at PnP.Core.Admin.Model.Teams.TeamCreator.CreateTeamForGroupAsync(PnPContext context, TeamForGroupOptions teamToCreate, TeamCreationOptions creationOptions)
[2022-06-20T18:13:36.619Z]    at PnP.Core.Admin.Model.Teams.TeamManager.CreateTeamAsync(TeamOptions teamToCreate, TeamCreationOptions creationOptions)

## Steps to reproduce

1. Create Team Site
2. Add Team using TeamManager `await PnPContext.GetTeamManager().CreateTeamAsync(teamOptions);`

## Expected behavior

The method should wait until the Team has actually been connected to the group.

## Environment details (*development & target environment*)

- **SDK version**: [ 1.6.83-nightly ]
- **OS**: [ Windows 11 ]
- **SDK used in**: [ Azure Function ]
- **Framework**: [.NET 6.0 ]
- **Browser(s)**: [ n/a ]
- **Tooling**: [ Visual Studio 2022 ]
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context
My method:
```csharp
public async Task<ITeam> AddTeamToGroupAsync()
    {
        // Find team if it already exists
        Guid groupId = new(PnPContext.Group.Id);
        try
        {
            ITeam team = await PnPContext.Team.GetAsync();
            Logger.LogInformation("Found existing team for group with id: {groupId}.", groupId);
            return team;
        }
        catch (ServiceException)
        {
            Logger.LogInformation("Could not find team for group with id {groupId}, adding new team.", groupId);
        }
        // Add team if it does not exist
        try
        {
            // Define settings for creation
            TeamForGroupOptions teamOptions = new(groupId);
            // Create team
            using PnPContext? contextWithTeam = await PnPContext.GetTeamManager().CreateTeamAsync(teamOptions);
            ITeam addedTeam = await contextWithTeam.Team.GetAsync(p => p.PrimaryChannel);
            return addedTeam;
        }
        catch (ServiceException ex)
        {
            Logger.LogError(ex.Error.ToString());
            throw;
        }
    }
```

**Comment by jansenbe** [comment]
@mortenostigard : The final GET should not require a retry when erroring, when you get to that point to Team should have been created (like you're noticing) otherwise an exception would have been thrown. The code retries the PUT 10 times with a wait time of 30 seconds in between, once a PUT was successful it tries to create a PnPContext.

Can you try to add a delay after the CreateTeamAsync call and see if that helps. Also please share a Fiddler trace of a failing operation (feel free to mail to bjansen@microsoft.com).

**Comment by mortenostigard** [comment]
I'm on vacation for another week, but will be having a look into it when I come back. As for now I have added another layer of retry handling as a quick fix..

**Comment by jansenbe** [comment]
@mortenostigard : do you have an update here or can we close this issue?

**Comment by jansenbe** [comment]
Closing per no feedback anymore. Feel free to re-open or create a new issue if the problems are not addressed properly
