### ISSUE TITLE
onBehalfOf login fail

### ISSUE THREAD

**Issue by aidanbha79** [pnp/pnpcore#972]
## Category

- [x] Bug

## Describe the bug

When I try and create a context using the onBehalfOf configuration i get an exception 

System.Configuration.ConfigurationErrorsException: Missing value for function UserTokenProvider in OnBehalfOfAuthenticationProvider
   at PnP.Core.Auth.OnBehalfOfAuthenticationProvider.GetAccessTokenAsync(Uri resource, String[] scopes)
   at PnP.Core.Auth.OnBehalfOfAuthenticationProvider.GetAccessTokenAsync(Uri resource)
   at PnP.Core.Auth.OnBehalfOfAuthenticationProvider.AuthenticateRequestAsync(Uri resource, HttpRequestMessage request)
   at PnP.Core.Services.BatchClient.ProcessSharePointRestAuthentication(Uri site, HttpRequestMessage request)
   at PnP.Core.Services.BatchClient.ExecuteSharePointRestInteractiveAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Model.BaseDataModel`1.RequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
   at PnP.Core.Services.PnPContextFactory.InitializeContextAsync(PnPContext context, PnPContextOptions options)
   at PnP.Core.Services.PnPContextFactory.CreateAsync(Uri url, IAuthenticationProvider authenticationProvider, CancellationToken cancellationToken, PnPContextOptions options)
   at PnP.Core.Services.PnPContextFactory.CreateAsync(String name, Action`1 initializeAuthenticationProvider, CancellationToken cancellationToken, PnPContextOptions options)
   at PnP.Core.Services.PnPContextFactory.CreateAsync(String name, PnPContextOptions options)

` "onBehalfOf": {
          "ClientId": "[my-app-ClientId]",
          "TenantId": "[my-app-TenantId]",
          "OnBehalfOf": {
            "ClientSecret": "[my-app-ClientSecret]"
          }
        }`

`builder.Services.AddPnPCore();
builder.Services.Configure<PnPCoreOptions>(builder.Configuration.GetSection("PnPCore"));
builder.Services.AddPnPCoreAuthentication();
builder.Services.Configure<PnPCoreAuthenticationOptions>(builder.Configuration.GetSection("PnPCore"));`

`return await _contextFactory.CreateAsync("SiteToWorkWith");`
## Environment details (*development & target environment*)

- **SDK version**: [e.g. 0.1.2005.0 ]
- **OS**: Windows 11
- **SDK used in**: ASP.Net Web api 
- **Framework**: .net 6.0 PnP.Core 1.7.0 PnP.Core.Auth 1.7.0
- **Browser(s)**: chrome
- **Tooling**: Visual Studio 2022
- **Additional details**: *The more context you can provide, the easier it is (and therefore quicker) to help.*

### Additional context

*Thanks for your contribution! Sharing is caring.*

**Comment by jansenbe** [comment]
@aidanbha79 : @s-KaiNet a while ago created [a nice sample](https://spblog.net/post/2020/12/10/how-to-access-sharepoint-data-from-azure-function-with-spfx-and-pnp-core) showing how to use the `OnBehalfOfAuthenticationProvider`, maybe that helps to get your issue resolved.

**Comment by aidanbha79** [comment]
@jansenbe thank you for the response, is there a reason its not working through the config section? I got it working with a certificate if I manually created the options in the program.cs file but I have seen its possible to just have it all done through the config section.

**Comment by aidanbha79** [comment]
![image](https://user-images.githubusercontent.com/99991740/191958226-d6c1dc56-6a19-4d31-a11f-3a2dbc8a713d.png)

it looks to be pulling in the config and details correctly just the UserTokenProvider is being set to null

**Comment by jansenbe** [comment]
@aidanbha79 : hope this helps: https://github.com/pnp/pnpcore/blob/dev/src/sdk/PnP.Core.Auth.Test/appsettings.copyme.json#L44-L59. This is the config we use for auth unit tests, which include on behalf of tests and tests using certificate based auth.

**Comment by jansenbe** [comment]
@aidanbha79 : closing this issue now, feel free re-open if above does not help

**Comment by aidanbha79** [comment]
@jansenbe The json file didn't work still got errors but worked around it by building up Authentication settings in the program/startup class. thank you for the help though.
