### ISSUE TITLE
Error using GetSearchConfigurationXml and GetSearchConfigurationAsyncXml

### ISSUE THREAD

**Issue by gavdgavd** [pnp/pnpcore#988]
## Category

- [x] Bug

## Describe the bug

Error using the GetSearchConfigurationXml and GetSearchConfigurationAsyncXml methods to dump a copy of the search configuration of SharePoint Sites and Webs

## Steps to reproduce

1. Using Visual Studio and CSharp, get the SharePoint Context (type PnPContext) 
2. Use the methods to dump the Site or Web search configuration:
       string xmlWebSearchConfig = myContext.Web.GetSearchConfigurationXml();
       string xmlWebSearchConfig = myContext.Web.GetSearchConfigurationXmlAsync().Result;
3. The first line produces the next error:

- - - -------------------------------------------------------------
PnP.Core.CsomServiceException
  HResult=0x80131500
  Message=CSOM service exception
  Source=PnP.Core
  StackTrace:
   at PnP.Core.Services.BatchClient.ProcessCsomBatchResponse(CsomBatch csomBatch, String batchResponse, HttpStatusCode statusCode)
   at PnP.Core.Services.BatchClient.<ExecuteCsomBatchAsync>d__63.MoveNext()
   at PnP.Core.Services.BatchClient.<ExecuteBatch>d__37.MoveNext()
   at PnP.Core.Model.BaseDataModel`1.<RequestAsync>d__96.MoveNext()
   at PnP.Core.Model.BaseDataModel`1.<RawRequestAsync>d__98.MoveNext()
   at PnP.Core.Model.SharePoint.Web.<GetSearchConfigurationXmlAsync>d__443.MoveNext()
   at PnP.Core.Model.SharePoint.Web.GetSearchConfigurationXml()
- - - -------------------------------------------------------------

4. The second line produces the next error:

- - - -------------------------------------------------------------
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (CSOM service exception)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
CsomServiceException: CSOM service exception
- - - -------------------------------------------------------------

5. The context is correctly built because the same context is used to call other methods without errors, for example the next query runs correctly:
       ISearchResult allSrchResult = myContext.Web.Search(mySearchOptions);

## Expected behavior

An XML string with the configuration of the search engine for the SharePoint Site Collection or the Web.

## Environment details (*development & target environment*)

- **SDK version**: PnP.Core 1.7.0, PnP.Core.Auth 1.7.0.
- **OS**: Windows Server 2022 Standard (21H2)
- **SDK used in**: Console App
- **Framework**: .NET Core v6
- **Browser(s)**: Chromium Edge v106.0.1370.37 (Official build) (64-bit)
- **Tooling**: Microsoft Visual Studio Enterprise 2022 (64-bit) - v17.3.5

### Additional context

None

**Comment by jansenbe** [comment]
@gavdgavd : what permissions does your app have? Can you catch the exception and cast the error attribute as a `CsomError` (see https://pnp.github.io/pnpcore/using-the-sdk/basics-errorhandling.html#catching-a-pnp-core-sdk-exception-and-getting-the-exception-details) so you can see what error was returned from the CSOM call.

**Comment by gavdgavd** [comment]
Hi Bert,
1 - The context is created using the "UsernamePasswordAuthenticationProvider" for the "DefaultAuthenticationProvider", and it uses a default "PnP Management Shell" AAD App Registration.
2 - Error returned from the call to "GetSearchConfigurationXml" using the try/catch that you mention:

HttpResponseCode: 200
Message: Internal Server Error
ClientRequestId: 72396da0-8096-2000-7987-9877fa2162e4
ErrorTypeName: "System.Exception"

PnP.Core.CsomServiceException: CSOM service exception
   at PnP.Core.Services.BatchClient.ProcessCsomBatchResponse(CsomBatch csomBatch, String batchResponse, HttpStatusCode statusCode)
   at PnP.Core.Services.BatchClient.ExecuteCsomBatchAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Model.BaseDataModel`1.RequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
   at PnP.Core.Model.BaseDataModel`1.RawRequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
   at PnP.Core.Model.SharePoint.Web.GetSearchConfigurationXmlAsync()
   at PnP.Core.Model.SharePoint.Web.GetSearchConfigurationXml()
   at Program.<<Main>$>g__SpCsPnPCoreSdk_SearchExportConfigTest|0_23() in C:\Projects\Repos\ROEM\Program.cs:line xxx

3 - The error returned from the call to "GetSearchConfigurationXmlAsync" generates an error of the type "System.AggregateException", not a "ServiceException". After catching the error, the message is:

System.AggregateException: One or more errors occurred. (CSOM service exception)
 ---> HttpResponseCode: 200
Message: Internal Server Error
ClientRequestId: 233a6da0-a0d3-2000-7987-94b648e2d777
ErrorTypeName: "System.Exception"

PnP.Core.CsomServiceException: CSOM service exception
   at PnP.Core.Services.BatchClient.ProcessCsomBatchResponse(CsomBatch csomBatch, String batchResponse, HttpStatusCode statusCode)
   at PnP.Core.Services.BatchClient.ExecuteCsomBatchAsync(Batch batch)
   at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch)
   at PnP.Core.Model.BaseDataModel`1.RequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
   at PnP.Core.Model.BaseDataModel`1.RawRequestAsync(ApiCall apiCall, HttpMethod method, String operationName)
   at PnP.Core.Model.SharePoint.Web.GetSearchConfigurationXmlAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Program.<<Main>$>g__SpCsPnPCoreSdk_SearchExportConfigTest|0_23() in C:\Projects\Repos\ROEM\Program.cs:line xxx


Many thanks for your help. Let me know if you need any other data.

**Comment by jansenbe** [comment]
@gavdgavd : I've tried both the site and web GetSearchConfigurationXml methods on my tenant and they do still return data without error. Can you confirm that for example PnP PowerShell still does return the data?

**Comment by jansenbe** [comment]
@gavdgavd : can you also repro the issue using other means as PnP Core SDK? Does it repro on all your tenants?

**Comment by gavdgavd** [comment]
Hi Bert. Apologies for the delay. Regarding your questions:
1 - Three methods from PnP PowerShell tested, using the same tenant and user:
     a - Get-PnPSearchSettings ==> working correctly
     b - Get-PnPSearchCrawlLog ==> working correctly
     c - Get-PnPSearchConfiguration ==> gets an exception: "Internal Server Error"
2 - Tried in two differente M365 tenants, with two different accounts in each tenant, and using context generated by UsernamePasswordAuthenticationProvider and by X509CertificateAuthenticationProvider with the same result.
Let me know if you need any other information. Thanks for your help.

**Comment by gavdgavd** [comment]
UPDATE: Juist tried with a new fresh M365 tenant, and the method works properly. It seems that it is a problem of tenant configuration. Trying to find the differences with the old tenants, but nothing found till now. Maybe can you try with an older (six month old of zo) tenant?
